{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "name": "Copy of Copy of Project_SML.ipynb",
      "provenance": [],
      "collapsed_sections": [],
      "authorship_tag": "ABX9TyMKJ2Of87crNkppkOczB/Xw",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/IZ001/Stat-Machine-Learning/blob/main/Code_for_the_report_of_Project_SML.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "source": [
        "Task2 \n",
        "\n",
        "Look into the provided data set by e.g. plotting the individual features. Based on your analysis,\n",
        "answer the following questions:\n",
        "\n",
        "• Do men or women dominate speaking roles in Hollywood movies?\n",
        "• Has gender balance in speaking roles changed over time (i.e. years)?\n",
        "• Do flms in which men do more speaking make a lot more money than flms in which women\n",
        "speak more?\n",
        "Write 1-2 sentences for each question and support your fndings with evidence (statistics, plots, ...).\n",
        "Based on your analysis, you should evaluate how the worst-case classifer for this problem is expected\n",
        "to perform. That is, the classifer that always randomly picks a class or always predicts the same\n",
        "output class."
      ],
      "metadata": {
        "id": "hIgkZprfaXsX"
      }
    },
    {
      "cell_type": "code",
      "source": [
        "import pandas as pd\n",
        "import numpy as np\n",
        "import matplotlib.pyplot as plt\n",
        "\n",
        "import sklearn.linear_model as skl_lm\n",
        "import sklearn.discriminant_analysis as skl_da\n",
        "import sklearn.neighbors as skl_nb\n",
        "import sklearn.preprocessing as skl_pre\n",
        "\n",
        "from google.colab import files\n",
        "uploaded = files.upload()\n",
        "\n",
        "import io\n",
        "data = pd.read_csv(io.BytesIO(uploaded['train.csv']), na_values = '?').dropna().reset_index(drop=True)\n",
        "# Dataset is now stored in a Pandas Dataframe\n",
        "\n",
        "#import seaborn as sns"
      ],
      "metadata": {
        "id": "36KgF2TCatph",
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 74,
          "resources": {
            "http://localhost:8080/nbextensions/google.colab/files.js": {
              "data": "Ly8gQ29weXJpZ2h0IDIwMTcgR29vZ2xlIExMQwovLwovLyBMaWNlbnNlZCB1bmRlciB0aGUgQXBhY2hlIExpY2Vuc2UsIFZlcnNpb24gMi4wICh0aGUgIkxpY2Vuc2UiKTsKLy8geW91IG1heSBub3QgdXNlIHRoaXMgZmlsZSBleGNlcHQgaW4gY29tcGxpYW5jZSB3aXRoIHRoZSBMaWNlbnNlLgovLyBZb3UgbWF5IG9idGFpbiBhIGNvcHkgb2YgdGhlIExpY2Vuc2UgYXQKLy8KLy8gICAgICBodHRwOi8vd3d3LmFwYWNoZS5vcmcvbGljZW5zZXMvTElDRU5TRS0yLjAKLy8KLy8gVW5sZXNzIHJlcXVpcmVkIGJ5IGFwcGxpY2FibGUgbGF3IG9yIGFncmVlZCB0byBpbiB3cml0aW5nLCBzb2Z0d2FyZQovLyBkaXN0cmlidXRlZCB1bmRlciB0aGUgTGljZW5zZSBpcyBkaXN0cmlidXRlZCBvbiBhbiAiQVMgSVMiIEJBU0lTLAovLyBXSVRIT1VUIFdBUlJBTlRJRVMgT1IgQ09ORElUSU9OUyBPRiBBTlkgS0lORCwgZWl0aGVyIGV4cHJlc3Mgb3IgaW1wbGllZC4KLy8gU2VlIHRoZSBMaWNlbnNlIGZvciB0aGUgc3BlY2lmaWMgbGFuZ3VhZ2UgZ292ZXJuaW5nIHBlcm1pc3Npb25zIGFuZAovLyBsaW1pdGF0aW9ucyB1bmRlciB0aGUgTGljZW5zZS4KCi8qKgogKiBAZmlsZW92ZXJ2aWV3IEhlbHBlcnMgZm9yIGdvb2dsZS5jb2xhYiBQeXRob24gbW9kdWxlLgogKi8KKGZ1bmN0aW9uKHNjb3BlKSB7CmZ1bmN0aW9uIHNwYW4odGV4dCwgc3R5bGVBdHRyaWJ1dGVzID0ge30pIHsKICBjb25zdCBlbGVtZW50ID0gZG9jdW1lbnQuY3JlYXRlRWxlbWVudCgnc3BhbicpOwogIGVsZW1lbnQudGV4dENvbnRlbnQgPSB0ZXh0OwogIGZvciAoY29uc3Qga2V5IG9mIE9iamVjdC5rZXlzKHN0eWxlQXR0cmlidXRlcykpIHsKICAgIGVsZW1lbnQuc3R5bGVba2V5XSA9IHN0eWxlQXR0cmlidXRlc1trZXldOwogIH0KICByZXR1cm4gZWxlbWVudDsKfQoKLy8gTWF4IG51bWJlciBvZiBieXRlcyB3aGljaCB3aWxsIGJlIHVwbG9hZGVkIGF0IGEgdGltZS4KY29uc3QgTUFYX1BBWUxPQURfU0laRSA9IDEwMCAqIDEwMjQ7CgpmdW5jdGlvbiBfdXBsb2FkRmlsZXMoaW5wdXRJZCwgb3V0cHV0SWQpIHsKICBjb25zdCBzdGVwcyA9IHVwbG9hZEZpbGVzU3RlcChpbnB1dElkLCBvdXRwdXRJZCk7CiAgY29uc3Qgb3V0cHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKG91dHB1dElkKTsKICAvLyBDYWNoZSBzdGVwcyBvbiB0aGUgb3V0cHV0RWxlbWVudCB0byBtYWtlIGl0IGF2YWlsYWJsZSBmb3IgdGhlIG5leHQgY2FsbAogIC8vIHRvIHVwbG9hZEZpbGVzQ29udGludWUgZnJvbSBQeXRob24uCiAgb3V0cHV0RWxlbWVudC5zdGVwcyA9IHN0ZXBzOwoKICByZXR1cm4gX3VwbG9hZEZpbGVzQ29udGludWUob3V0cHV0SWQpOwp9CgovLyBUaGlzIGlzIHJvdWdobHkgYW4gYXN5bmMgZ2VuZXJhdG9yIChub3Qgc3VwcG9ydGVkIGluIHRoZSBicm93c2VyIHlldCksCi8vIHdoZXJlIHRoZXJlIGFyZSBtdWx0aXBsZSBhc3luY2hyb25vdXMgc3RlcHMgYW5kIHRoZSBQeXRob24gc2lkZSBpcyBnb2luZwovLyB0byBwb2xsIGZvciBjb21wbGV0aW9uIG9mIGVhY2ggc3RlcC4KLy8gVGhpcyB1c2VzIGEgUHJvbWlzZSB0byBibG9jayB0aGUgcHl0aG9uIHNpZGUgb24gY29tcGxldGlvbiBvZiBlYWNoIHN0ZXAsCi8vIHRoZW4gcGFzc2VzIHRoZSByZXN1bHQgb2YgdGhlIHByZXZpb3VzIHN0ZXAgYXMgdGhlIGlucHV0IHRvIHRoZSBuZXh0IHN0ZXAuCmZ1bmN0aW9uIF91cGxvYWRGaWxlc0NvbnRpbnVlKG91dHB1dElkKSB7CiAgY29uc3Qgb3V0cHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKG91dHB1dElkKTsKICBjb25zdCBzdGVwcyA9IG91dHB1dEVsZW1lbnQuc3RlcHM7CgogIGNvbnN0IG5leHQgPSBzdGVwcy5uZXh0KG91dHB1dEVsZW1lbnQubGFzdFByb21pc2VWYWx1ZSk7CiAgcmV0dXJuIFByb21pc2UucmVzb2x2ZShuZXh0LnZhbHVlLnByb21pc2UpLnRoZW4oKHZhbHVlKSA9PiB7CiAgICAvLyBDYWNoZSB0aGUgbGFzdCBwcm9taXNlIHZhbHVlIHRvIG1ha2UgaXQgYXZhaWxhYmxlIHRvIHRoZSBuZXh0CiAgICAvLyBzdGVwIG9mIHRoZSBnZW5lcmF0b3IuCiAgICBvdXRwdXRFbGVtZW50Lmxhc3RQcm9taXNlVmFsdWUgPSB2YWx1ZTsKICAgIHJldHVybiBuZXh0LnZhbHVlLnJlc3BvbnNlOwogIH0pOwp9CgovKioKICogR2VuZXJhdG9yIGZ1bmN0aW9uIHdoaWNoIGlzIGNhbGxlZCBiZXR3ZWVuIGVhY2ggYXN5bmMgc3RlcCBvZiB0aGUgdXBsb2FkCiAqIHByb2Nlc3MuCiAqIEBwYXJhbSB7c3RyaW5nfSBpbnB1dElkIEVsZW1lbnQgSUQgb2YgdGhlIGlucHV0IGZpbGUgcGlja2VyIGVsZW1lbnQuCiAqIEBwYXJhbSB7c3RyaW5nfSBvdXRwdXRJZCBFbGVtZW50IElEIG9mIHRoZSBvdXRwdXQgZGlzcGxheS4KICogQHJldHVybiB7IUl0ZXJhYmxlPCFPYmplY3Q+fSBJdGVyYWJsZSBvZiBuZXh0IHN0ZXBzLgogKi8KZnVuY3Rpb24qIHVwbG9hZEZpbGVzU3RlcChpbnB1dElkLCBvdXRwdXRJZCkgewogIGNvbnN0IGlucHV0RWxlbWVudCA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKGlucHV0SWQpOwogIGlucHV0RWxlbWVudC5kaXNhYmxlZCA9IGZhbHNlOwoKICBjb25zdCBvdXRwdXRFbGVtZW50ID0gZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQob3V0cHV0SWQpOwogIG91dHB1dEVsZW1lbnQuaW5uZXJIVE1MID0gJyc7CgogIGNvbnN0IHBpY2tlZFByb21pc2UgPSBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4gewogICAgaW5wdXRFbGVtZW50LmFkZEV2ZW50TGlzdGVuZXIoJ2NoYW5nZScsIChlKSA9PiB7CiAgICAgIHJlc29sdmUoZS50YXJnZXQuZmlsZXMpOwogICAgfSk7CiAgfSk7CgogIGNvbnN0IGNhbmNlbCA9IGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ2J1dHRvbicpOwogIGlucHV0RWxlbWVudC5wYXJlbnRFbGVtZW50LmFwcGVuZENoaWxkKGNhbmNlbCk7CiAgY2FuY2VsLnRleHRDb250ZW50ID0gJ0NhbmNlbCB1cGxvYWQnOwogIGNvbnN0IGNhbmNlbFByb21pc2UgPSBuZXcgUHJvbWlzZSgocmVzb2x2ZSkgPT4gewogICAgY2FuY2VsLm9uY2xpY2sgPSAoKSA9PiB7CiAgICAgIHJlc29sdmUobnVsbCk7CiAgICB9OwogIH0pOwoKICAvLyBXYWl0IGZvciB0aGUgdXNlciB0byBwaWNrIHRoZSBmaWxlcy4KICBjb25zdCBmaWxlcyA9IHlpZWxkIHsKICAgIHByb21pc2U6IFByb21pc2UucmFjZShbcGlja2VkUHJvbWlzZSwgY2FuY2VsUHJvbWlzZV0pLAogICAgcmVzcG9uc2U6IHsKICAgICAgYWN0aW9uOiAnc3RhcnRpbmcnLAogICAgfQogIH07CgogIGNhbmNlbC5yZW1vdmUoKTsKCiAgLy8gRGlzYWJsZSB0aGUgaW5wdXQgZWxlbWVudCBzaW5jZSBmdXJ0aGVyIHBpY2tzIGFyZSBub3QgYWxsb3dlZC4KICBpbnB1dEVsZW1lbnQuZGlzYWJsZWQgPSB0cnVlOwoKICBpZiAoIWZpbGVzKSB7CiAgICByZXR1cm4gewogICAgICByZXNwb25zZTogewogICAgICAgIGFjdGlvbjogJ2NvbXBsZXRlJywKICAgICAgfQogICAgfTsKICB9CgogIGZvciAoY29uc3QgZmlsZSBvZiBmaWxlcykgewogICAgY29uc3QgbGkgPSBkb2N1bWVudC5jcmVhdGVFbGVtZW50KCdsaScpOwogICAgbGkuYXBwZW5kKHNwYW4oZmlsZS5uYW1lLCB7Zm9udFdlaWdodDogJ2JvbGQnfSkpOwogICAgbGkuYXBwZW5kKHNwYW4oCiAgICAgICAgYCgke2ZpbGUudHlwZSB8fCAnbi9hJ30pIC0gJHtmaWxlLnNpemV9IGJ5dGVzLCBgICsKICAgICAgICBgbGFzdCBtb2RpZmllZDogJHsKICAgICAgICAgICAgZmlsZS5sYXN0TW9kaWZpZWREYXRlID8gZmlsZS5sYXN0TW9kaWZpZWREYXRlLnRvTG9jYWxlRGF0ZVN0cmluZygpIDoKICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgJ24vYSd9IC0gYCkpOwogICAgY29uc3QgcGVyY2VudCA9IHNwYW4oJzAlIGRvbmUnKTsKICAgIGxpLmFwcGVuZENoaWxkKHBlcmNlbnQpOwoKICAgIG91dHB1dEVsZW1lbnQuYXBwZW5kQ2hpbGQobGkpOwoKICAgIGNvbnN0IGZpbGVEYXRhUHJvbWlzZSA9IG5ldyBQcm9taXNlKChyZXNvbHZlKSA9PiB7CiAgICAgIGNvbnN0IHJlYWRlciA9IG5ldyBGaWxlUmVhZGVyKCk7CiAgICAgIHJlYWRlci5vbmxvYWQgPSAoZSkgPT4gewogICAgICAgIHJlc29sdmUoZS50YXJnZXQucmVzdWx0KTsKICAgICAgfTsKICAgICAgcmVhZGVyLnJlYWRBc0FycmF5QnVmZmVyKGZpbGUpOwogICAgfSk7CiAgICAvLyBXYWl0IGZvciB0aGUgZGF0YSB0byBiZSByZWFkeS4KICAgIGxldCBmaWxlRGF0YSA9IHlpZWxkIHsKICAgICAgcHJvbWlzZTogZmlsZURhdGFQcm9taXNlLAogICAgICByZXNwb25zZTogewogICAgICAgIGFjdGlvbjogJ2NvbnRpbnVlJywKICAgICAgfQogICAgfTsKCiAgICAvLyBVc2UgYSBjaHVua2VkIHNlbmRpbmcgdG8gYXZvaWQgbWVzc2FnZSBzaXplIGxpbWl0cy4gU2VlIGIvNjIxMTU2NjAuCiAgICBsZXQgcG9zaXRpb24gPSAwOwogICAgZG8gewogICAgICBjb25zdCBsZW5ndGggPSBNYXRoLm1pbihmaWxlRGF0YS5ieXRlTGVuZ3RoIC0gcG9zaXRpb24sIE1BWF9QQVlMT0FEX1NJWkUpOwogICAgICBjb25zdCBjaHVuayA9IG5ldyBVaW50OEFycmF5KGZpbGVEYXRhLCBwb3NpdGlvbiwgbGVuZ3RoKTsKICAgICAgcG9zaXRpb24gKz0gbGVuZ3RoOwoKICAgICAgY29uc3QgYmFzZTY0ID0gYnRvYShTdHJpbmcuZnJvbUNoYXJDb2RlLmFwcGx5KG51bGwsIGNodW5rKSk7CiAgICAgIHlpZWxkIHsKICAgICAgICByZXNwb25zZTogewogICAgICAgICAgYWN0aW9uOiAnYXBwZW5kJywKICAgICAgICAgIGZpbGU6IGZpbGUubmFtZSwKICAgICAgICAgIGRhdGE6IGJhc2U2NCwKICAgICAgICB9LAogICAgICB9OwoKICAgICAgbGV0IHBlcmNlbnREb25lID0gZmlsZURhdGEuYnl0ZUxlbmd0aCA9PT0gMCA/CiAgICAgICAgICAxMDAgOgogICAgICAgICAgTWF0aC5yb3VuZCgocG9zaXRpb24gLyBmaWxlRGF0YS5ieXRlTGVuZ3RoKSAqIDEwMCk7CiAgICAgIHBlcmNlbnQudGV4dENvbnRlbnQgPSBgJHtwZXJjZW50RG9uZX0lIGRvbmVgOwoKICAgIH0gd2hpbGUgKHBvc2l0aW9uIDwgZmlsZURhdGEuYnl0ZUxlbmd0aCk7CiAgfQoKICAvLyBBbGwgZG9uZS4KICB5aWVsZCB7CiAgICByZXNwb25zZTogewogICAgICBhY3Rpb246ICdjb21wbGV0ZScsCiAgICB9CiAgfTsKfQoKc2NvcGUuZ29vZ2xlID0gc2NvcGUuZ29vZ2xlIHx8IHt9OwpzY29wZS5nb29nbGUuY29sYWIgPSBzY29wZS5nb29nbGUuY29sYWIgfHwge307CnNjb3BlLmdvb2dsZS5jb2xhYi5fZmlsZXMgPSB7CiAgX3VwbG9hZEZpbGVzLAogIF91cGxvYWRGaWxlc0NvbnRpbnVlLAp9Owp9KShzZWxmKTsK",
              "ok": true,
              "headers": [
                [
                  "content-type",
                  "application/javascript"
                ]
              ],
              "status": 200,
              "status_text": ""
            }
          }
        },
        "outputId": "670f6980-06fa-43b1-ca84-91779c352f42"
      },
      "execution_count": 1,
      "outputs": [
        {
          "output_type": "display_data",
          "data": {
            "text/html": [
              "\n",
              "     <input type=\"file\" id=\"files-8bd51728-0844-4a14-bcb1-5178e8577179\" name=\"files[]\" multiple disabled\n",
              "        style=\"border:none\" />\n",
              "     <output id=\"result-8bd51728-0844-4a14-bcb1-5178e8577179\">\n",
              "      Upload widget is only available when the cell has been executed in the\n",
              "      current browser session. Please rerun this cell to enable.\n",
              "      </output>\n",
              "      <script src=\"/nbextensions/google.colab/files.js\"></script> "
            ],
            "text/plain": [
              "<IPython.core.display.HTML object>"
            ]
          },
          "metadata": {}
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Saving train.csv to train.csv\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "data['Lead'] = np.where(data['Lead'] == 'Female', 1, 0)"
      ],
      "metadata": {
        "id": "w1aOrgywWe5W"
      },
      "execution_count": 2,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Split the data randomly into a training set and a test set of approximately similar size.\n",
        "\n",
        "np.random.seed(1)\n",
        "trainI = np.random.choice(data.shape[0], size= 700, replace=False)\n",
        "trainIndex = data.index.isin(trainI)\n",
        "\n",
        "train = data.iloc[trainIndex]\n",
        "test = data.iloc[~trainIndex]"
      ],
      "metadata": {
        "id": "7Yw0Plriym7V"
      },
      "execution_count": 3,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# Try different feature sets (with data scaling)\n",
        "\n",
        "import itertools\n",
        "def findsubsets(s, n):\n",
        "    return list(itertools.combinations(s, n))\n",
        "\n",
        "from sklearn.metrics import roc_auc_score\n",
        "from sklearn.metrics import auc\n",
        "from sklearn.metrics import precision_recall_curve\n",
        "\n",
        "min_error = data.shape[0]\n",
        "error_a = 0\n",
        "features_max = []\n",
        "coef =0\n",
        "conf_matrix =0\n",
        "chosen_model =0\n",
        "prob = 0\n",
        "\n",
        "pc_auc = 0\n",
        "roc_auc = 0\n",
        "f1 = 0\n",
        "roc_auc_a = 0\n",
        "pc_auc_a = 0\n",
        "pc_auc_max = 0\n",
        "roc_auc_max = 0\n",
        "f1_a = 0\n",
        "\n",
        "s = {'Number words female', 'Total words', 'Number of words lead', 'Difference in words lead and co-lead', 'Number of male actors', 'Year', 'Number of female actors', 'Number words male', 'Gross', 'Mean Age Male', 'Mean Age Female','Age Lead', 'Age Co-Lead'}\n",
        "n = 13\n",
        "\n",
        "# define model\n",
        "model = skl_lm.LogisticRegression(solver ='liblinear')\n",
        "\n",
        "subsets = findsubsets(s, n)\n",
        "for s in subsets:\n",
        "  input_variables = list(s)\n",
        "\n",
        "  x_train = train[input_variables]\n",
        "  y_train = train['Lead']\n",
        "  x_test = test[input_variables]\n",
        "  y_test = test['Lead']\n",
        "\n",
        "  scaler = skl_pre.StandardScaler().fit(x_train)\n",
        "  model.fit(scaler.transform(x_train), y_train )\n",
        "  predict_prob = model.predict_proba(scaler.transform(x_test))\n",
        "  prediction = np.where(predict_prob[:,1] > 0.5, 1, 0)\n",
        "  \n",
        "  #Misclassification error\n",
        "  error = np.mean(prediction != y_test)\n",
        "\n",
        "  # calculate roc auc\n",
        "  roc_auc = roc_auc_score(y_test, predict_prob[:,1])\n",
        "\n",
        "  # calculate the precision-recall auc\n",
        "  precision, recall, _ = precision_recall_curve(y_test, predict_prob[:,1])\n",
        "  pc_auc = auc(recall, precision)\n",
        "  f1 = f1 = 2*precision*recall/(precision+recall)\n",
        "\n",
        "  # chose the model with the max ROC AUC\n",
        "  if roc_auc > roc_auc_max:\n",
        "    roc_auc_max = roc_auc\n",
        "    error_a = error\n",
        "    features_max = input_variables\n",
        "    chosen_model = model\n",
        "    conf_matrix = pd.crosstab(prediction, y_test)\n",
        "    prob = predict_prob\n",
        "    pc_auc_a = pc_auc\n",
        "    f1_a = f1\n",
        "\n",
        "#print(f1_a)\n",
        "print(features_max)\n",
        "print('Misclassification error',error_a)\n",
        "print(f'ROC AUC = {roc_auc_max}')\n",
        "print('PC AUC =', pc_auc_a)\n",
        "print('F1 =', np.max(f1_a))\n",
        "print(chosen_model.coef_)\n",
        "print(chosen_model.classes_)\n",
        "print(conf_matrix)\n",
        "\n",
        "\n"
      ],
      "metadata": {
        "id": "yoEKzV0QynKX",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "e4efb935-1565-4ca8-ac85-38d0b1cd2326"
      },
      "execution_count": 4,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "['Gross', 'Number of male actors', 'Mean Age Male', 'Year', 'Number words male', 'Number of female actors', 'Number of words lead', 'Age Co-Lead', 'Difference in words lead and co-lead', 'Total words', 'Mean Age Female', 'Number words female', 'Age Lead']\n",
            "Misclassification error 0.1415929203539823\n",
            "ROC AUC = 0.879980079681275\n",
            "PC AUC = 0.7768441684891018\n",
            "F1 = 0.7012987012987013\n",
            "[[-0.05366148 -1.31008883  0.2165877  -0.00853541  0.65896931  1.565523\n",
            "   1.02174695  0.57172322 -1.60649287  0.24791482  0.04697703 -1.61633581\n",
            "  -0.76838017]]\n",
            "[0 1]\n",
            "Lead     0   1\n",
            "row_0         \n",
            "0      240  37\n",
            "1       11  51\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "X = data\n",
        "y = data['Lead']"
      ],
      "metadata": {
        "id": "FYdg27_zOQ5N"
      },
      "execution_count": 5,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "import sklearn.model_selection as skl_ms\n",
        "import sklearn.preprocessing as skl_pre\n",
        "n_runs = 20\n",
        "features_lsts_with_big_roc_auc =[]\n",
        "s = {'Number words female', 'Total words', 'Number of words lead', 'Difference in words lead and co-lead', 'Number of male actors', 'Year', 'Number of female actors', 'Number words male', 'Gross', 'Mean Age Male', 'Mean Age Female','Age Lead', 'Age Co-Lead'}\n",
        "\n",
        "#s - set with all variables, n -number of variables in subsets\n",
        "subsets_1 = findsubsets(s, 8)\n",
        "subsets_2 = findsubsets(s, 9)\n",
        "subsets_3 = findsubsets(s, 10)\n",
        "\n",
        "subsets = subsets_1 + subsets_2 + subsets_3\n",
        "roc_auc_n = np.zeros((n_runs, len(subsets)))\n",
        "pc_auc = 0\n",
        "error = 0\n",
        "pc_auc = 0\n",
        "f1 = 0\n",
        "\n",
        "for i in range(n_runs):\n",
        "  X_train, X_val, y_train, y_val = skl_ms.train_test_split(X, y, test_size = 0.3)\n",
        "  \n",
        "  for j, s in enumerate(subsets):\n",
        "    input_variables = list(s)\n",
        "      \n",
        "    x_train = X_train[input_variables]\n",
        "    x_test = X_val[input_variables]\n",
        "    y_test = y_val\n",
        "\n",
        "    model = skl_lm.LogisticRegression(solver ='liblinear')\n",
        "    scaler = skl_pre.StandardScaler().fit(x_train)\n",
        "\n",
        "    model.fit(scaler.transform(x_train), y_train)\n",
        "    predict_prob = model.predict_proba(scaler.transform(x_test))\n",
        "    prediction = np.where(predict_prob[:,1] > 0.5, 1, 0)\n",
        "\n",
        "    # calculate roc auc\n",
        "    roc_auc = roc_auc_score(y_test, predict_prob[:,1])\n",
        "    roc_auc_n[i,j] = roc_auc\n",
        "\n",
        "roc_auc_avg = np.mean(roc_auc_n, axis = 0)\n",
        "\n",
        "for idx ,el in enumerate(roc_auc_avg):\n",
        "  if el > np.max(roc_auc_avg)*(1-0.001):\n",
        "    features_lsts_with_big_roc_auc.append(list(subsets[idx]))\n",
        "\n",
        "for el in features_lsts_with_big_roc_auc:\n",
        "  print(el)\n",
        "  print('Number of features',len(el))\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "HChugzfG8XnU",
        "outputId": "620da664-ba10-4c60-e00c-dd85a30f0cd0"
      },
      "execution_count": 6,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "['Number of male actors', 'Mean Age Male', 'Number of female actors', 'Number of words lead', 'Age Co-Lead', 'Difference in words lead and co-lead', 'Number words female', 'Age Lead']\n",
            "Number of features 8\n",
            "['Number of male actors', 'Number words male', 'Number of female actors', 'Number of words lead', 'Age Co-Lead', 'Difference in words lead and co-lead', 'Number words female', 'Age Lead']\n",
            "Number of features 8\n",
            "['Number of male actors', 'Number of female actors', 'Number of words lead', 'Age Co-Lead', 'Difference in words lead and co-lead', 'Total words', 'Number words female', 'Age Lead']\n",
            "Number of features 8\n",
            "['Number of male actors', 'Mean Age Male', 'Number of female actors', 'Number of words lead', 'Age Co-Lead', 'Difference in words lead and co-lead', 'Total words', 'Number words female', 'Age Lead']\n",
            "Number of features 9\n",
            "['Number of male actors', 'Number words male', 'Number of female actors', 'Number of words lead', 'Age Co-Lead', 'Difference in words lead and co-lead', 'Total words', 'Number words female', 'Age Lead']\n",
            "Number of features 9\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# find the decision threshold \n",
        "def find_r(prob, y_test):\n",
        "  recall = []\n",
        "  precision = []\n",
        "  f1_max = 0\n",
        "  r_f1 = 0\n",
        "\n",
        "  positive_class = 1\n",
        "  negative_class = 0\n",
        "\n",
        "  P = np.sum(y_test == positive_class)\n",
        "  prediction = np.empty(len(x_test), dtype ='object')\n",
        "  tr_val = np.linspace(0.00 , 1, num =101)\n",
        "\n",
        "  for r in tr_val:\n",
        "    prediction = np.where(prob[:,1] > r, positive_class, negative_class)\n",
        "    P_star = np.sum(prediction == positive_class)\n",
        "    tr_pos = np.sum((prediction == y_test)&(prediction == positive_class))\n",
        "\n",
        "    rec = tr_pos/P\n",
        "    prec = tr_pos/P_star\n",
        "    \n",
        "    f1 = 2*prec*rec/(prec+rec)\n",
        "    if f1_max < f1:\n",
        "      f1_max =f1\n",
        "      r_f1 = r\n",
        "    \n",
        "  return r_f1\n",
        "\n",
        "# cross-validation of r\n",
        "#import sklearn.model_selection as skl_ms\n",
        "\n",
        "def calculate_average_r(features, X, y):\n",
        "# features -list of features\n",
        "# X - data with all features\n",
        "# y - column 'Lead'\n",
        "  n_runs = 10\n",
        "\n",
        "  tr_rates_n = np.zeros((n_runs))\n",
        "  for i in range(n_runs):\n",
        "\n",
        "    X_train, X_val, y_train, y_val = skl_ms.train_test_split(X, y, test_size = 0.3)\n",
        "    model = skl_lm.LogisticRegression(solver ='liblinear')\n",
        "    scaler = skl_pre.StandardScaler().fit(X_train[features])\n",
        "    model.fit(scaler.transform(X_train[features]), y_train)\n",
        "    predict_prob = model.predict_proba(scaler.transform(X_val[features]))\n",
        "    \n",
        "    tr_rates_n[i] = find_r(predict_prob, y_val)\n",
        "\n",
        "  return np.average(tr_rates_n)"
      ],
      "metadata": {
        "id": "H80D_C65BJZY"
      },
      "execution_count": 7,
      "outputs": []
    },
    {
      "cell_type": "code",
      "source": [
        "# cross-validation of models with k-fold \n",
        "\n",
        "#import sklearn.model_selection as skl_ms\n",
        "features_list = features_lsts_with_big_roc_auc\n",
        "\n",
        "n_runs = 10\n",
        "\n",
        "pc_auc_n =np.zeros((n_runs, len(features_list)))\n",
        "roc_auc_n = np.zeros((n_runs, len(features_list)))\n",
        "misclassification_n = np.zeros((n_runs, len(features_list)))\n",
        "tr_rate_models = []\n",
        "\n",
        "X = data.drop(columns = 'Lead')\n",
        "y = data['Lead']\n",
        "\n",
        "n_fold = 10\n",
        "cv = skl_ms.KFold(n_splits = n_fold, random_state = 1, shuffle = True)\n",
        "\n",
        "for i, (train_index, val_index) in enumerate(cv.split(X)):\n",
        "  X_train, X_val = X.iloc[train_index], X.iloc[val_index]\n",
        "  y_train, y_val = y.iloc[train_index], y.iloc[val_index]\n",
        "\n",
        "  for j,features in enumerate(features_list):\n",
        "    model = skl_lm.LogisticRegression(solver ='liblinear')\n",
        "    scaler = skl_pre.StandardScaler().fit(X_train[features])\n",
        "    model.fit(scaler.transform(X_train[features]), y_train)\n",
        "    predict_prob = model.predict_proba(scaler.transform(X_val[features]))\n",
        "\n",
        "    # calculate the metrics\n",
        "    precision, recall, _ = precision_recall_curve(y_val, predict_prob[:,1])\n",
        "    pc_auc_n[i,j] = auc(recall, precision)\n",
        "    roc_auc_n[i,j] = roc_auc_score(y_val, predict_prob[:,1])  \n",
        "\n",
        "    tr_rate = calculate_average_r(features, X, y)\n",
        "    prediction = np.where(predict_prob[:,1] > tr_rate, 1, 0)\n",
        "    misclassification_n[i,j] = (np.mean(prediction != y_val))\n",
        "    tr_rate_models.append(tr_rate)   # make table to count average\n",
        "\n",
        "fig, axs = plt.subplots(1, 3, figsize=(12, 3), sharey=False)\n",
        "axs[0].boxplot(roc_auc_n)\n",
        "axs[1].boxplot(pc_auc_n)\n",
        "axs[2].boxplot(misclassification_n)\n",
        "\n",
        "fig.suptitle('Cross validation for models with different features sets')\n",
        "plt.show()\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 1000
        },
        "id": "k21AA_thiWmX",
        "outputId": "800e98d1-87c8-4117-a48d-b6e42f050c53"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAskAAADYCAYAAAAZIH76AAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3dfZxdVX3v8c83IRBEHhISvWAMiVXrkMBFGalcIjhQaOB6QS1oBnyInRK91VyvD63wGh8iOgV7fcBGq0YCCMggjcWmhRZpM0ijoAkYAsmIBkQIQQkkCIhAEn73j70m7Dk5M7Nn5sycfWa+79frvOac/bD2b+999jm/WWfttRQRmJmZmZnZCybUOwAzMzMzs7JxkmxmZmZmVsFJspmZmZlZBSfJZmZmZmYVnCSbmZmZmVVwkmxmZmZmVsFJstkYJelNkjbnXm+Q9KYiyw5hW9+Q9Mmhrt9PuZJ0maTtkn5a6/JrTdL9kv60wHKzJIWkvUYojn7Ph6Qlkq4aRvk3S/rL9PwcST/IzTtO0i8lPSXpLZJeKukWSU9K+uJQtzlSyh6fmdXPiHxAmzUySWcDHwFeAzwJrAM6ImJ1XQMbpoiYU4tyJC0E/jIi5uXKfn8tyq5iHnAyMCMifj9C2xhz8ucj/WN0VUTMGKFtfQf4Tm7SBcBXI+IrafufBB4FDohR7pi/2nu1ikXUKD5JlwObI+ITwymnXiTNAn4FTIqInfWNxqz+XJNsliPpI8DFwN8CLwVmAv8AnNHH8v5Hc2QdBtw/lATZ56ZuDgM2VLzeOJQEdJTO4ZDjqzW/Z81KJiL88MOPCIADgaeAs/pZZgmwArgKeAL4S+BQYCWwDdgEnJtb/hhgbVr2t8CX0vTJqYzHgMeBNcBLq2zv48CKimlfAf4+PX8v0E1W430f8L7ccm8iq9XqeX0/8Kfp+b7A5cB2YCPw1xXLngfcm8rdCLw1TW8CngF2pWP1eJp+OfC53PrnpmOxLR2bQ3PzAng/8Mu0718DVGXf2yq29ZmCZX8glf2rKmXOSsu8F3gw7f/7gdcD61M8X80tPwH4BPBr4BHgCuDA3Px3pXmPAe0Vx3hC7jg+BlwLTK2IY6/0emE6f0+S1eSdUyX2ycAfgGnpdTuwk6wGFOCzwMX58wHsl9Z5Ph3Dp8jer0tSPFekbW4Amvt5358M/Bz4HfBV4IdkNbQ9sa9Oz+9N2/pD2lYnsAN4Lr3+04LHpQ14ALglTf8Lsvf5duBG4LCB3k/08V6t2K/LBxNfWucfgd+kY3ELMCdNX1RR1r/k4ntlxTY/l79Gya7z3wBXDnB8Cn1u5D47Hkrn9x7gpALvywdSvD3vlWOBV6bz/TuyGvfv1vuz2g8/RutR9wD88KMsD2A+WdKxVz/LLElfhG9JXzb7pi/Kf0hfYEcBW4ET0/K3Au9Kz18MvCE9fx/wL8CLgInA0aRkp2J7hwFPA/un1xOBh3Pl/E/gj1JScEJa9nVp3pvoO0m+CPgvYCrwcuDuimXPIkumJgDvAH4PHJLmLSQlRbnl81/8J6Yv09cB+wBLSclOmh/AvwIHkdXUbwXm93G8e22rYNk3pf3at0p5s9Iy30jn6xSyROr7wEuAl5Elwyek5f+CLCF/RTp//wRcmeYdTpZIHJ9i+RLZ+6fnGH8IuA2YkeZ/E+isiGMvskT2CeCP07xDSIlXlfhvAf48Pf8BWaJzam7eW6ucj17vg9z7+BngNLL31IXAbX1scxpZonUmMAn4cNrPPZLkyvdZZSyDOC5XpOOyL9mvOJvIkt69yP5p+XGR91NlbH3sX+H4cu+J/dO8i4F1fZWVi6+/JHkn8PlU3r4DHJ+inxt/TPZP4KG54/pHg3lf5srqJPuHbALZNTNvpD+L/fCjLA83tzB7wcHAozFwW7xbI+L7EfE8WQJxHPDxiHgmItYBlwDvTsvuAF4paVpEPBURt+WmH0z25bkrIm6PiCcqNxQRvwbuAN6aJp0IPN1TTkRcHxH3RuaHZInTGwvs69vJ2llvi4gHgb+v2O4/RsSWiHg+Ir5LVkt3TIFyAc4BLo2IOyLiWeB84NjU3rHHRRHxeEQ8AHSR/XNRq7IvTPv1h37K+Ww6Xz8g+wegMyIeiYiHyP55eG1ue1+KiPsi4qm0vQXpZ/EzgX+NiFtSLJ8kq0Xt8X6gPSI2p/lLgDP7+En9eWCupH0j4uGI2FBlGchq9E5IZRxJdt5OkDSZrDb8ln72udLqiLghInaR1WD+9z6WOw3YEBErImIHWWL4m0Fsp1KR47IkIn6fzuH7yc5pd7o2/xY4StJhueWH+n4adHwRcWlEPJmb998lHTiM7T0PfDoins3tb1/bL/S5QVZ7vg9wuKRJEXF/RNxbZP+q2EH2z/qh6Zpp6HszzAbDSbLZCx4DphVoF/hg7vmhwLaIeDI37ddkNZKQ/Wz8auDnktZIenOafiXZz8bXSNoi6e8kTepje1cDren52ek1AJJOlXSbpG2SHidLaKYNEH9P3Pn9+HV+pqR3S1on6fFU7tyC5faUvbu8lFw+xgvHBHonWU+T1dLWquwHK1eq4re553+o8ronnl7bS8/3Imuv3usYRtZu+rHcsocB1+WOYTdZ8vLSfCBpvXeQJS8PS7pe0mv6iPuHZLWPrwPuIqs1PwF4A7ApIh7rY71qKs/B5D7e+5X7GRQ7xn0pclwerFj+K7nlt5H9clKL99Og4pM0UdJFku6V9ARZrTkUvzaq2RoRzxTZPgU/NyJiE/B/yRLgRyRdI+nQAuVX8zdkx/unqYecvxjGvpo1FCfJZi+4FXiWrClFfyL3fAswVdL+uWkzydoCEhG/jIhWsp/yPw+skLRfROyIiM9ExOHA/wDezAu1z5X+EXiTpBlkNcpXA0jaB/ge8AWydokHATeQfaEN5GGyZhb5mEnlHgZ8C/ggcHAq9+5cufn9r2YL2RdxT3n7kdV+PVQgroEUKXug+Ia8PbLjtJMsqe51DCW9KMXS40GyphAH5R6TU211LxFxY0ScTNbU4udkx7+aH5P9lP5W4IcRsTHFdBpZAl3NcI9H5X6K3u+dwSpyXKJi+fdVLL9vRPy4wLaGsu/9xXc2WfOPPyW7h2FWWqe/a+NpsuYRPf7bADH2uf3BfG5ExNWR9epxWNrG5wvs3x7xR8RvIuLciDiUrLnHP0h6ZbVtmo01TpLNkoj4HfAp4Gupf9cXSZqUamv/ro91HiRLXC6UNFnSkWS1x1cBSHqnpOmRNc14PK32vKQWSUdImkjWHnUHvX+qz29jK3AzcBnZzWjdadbeZD+pbgV2SjqVrI1tEdcC50uakpLvxbl5+5F9WW5N+/BesprkHr8FZkjau4+yO4H3SjoqJfJ/C/wkIu4vGFt/RrLsvrb3YUmzJb04be+76Wf/FcCbJc1Lx+ICen+mfgPo6GkWIGm6pD16SUn99J6REv5nydo59/VeeBq4nezmxJ6k+MdktdB9Jcm/BQ4eRpOA64E5kt6Wapr/D3smeoNR6LhULH++pDlp+QMlnVVwWwO9Vwcb3/5k5+gxssT3b6ts7xUV09YBZ6da6PlkNf9D2n7Rzw1JfyzpxHSNPMMLN28OtH9b03KvyJV1VvqMgOzGyai2TbOxyEmyWU5EfJGsj+RPkH1hPEhWo/r9flZrJatR2gJcR9a+8D/SvPnABklPkfVKsSC1O/xvZEnWE2Q/d/6Q7KfUvlxNVnu1u6lFauLxf8gS3u1ktVwrC+7qZ8iaDvyKrB3z7m2n2skvktWs/xY4AvhRbt1VZL0h/EbSo5UFp33/JFkt98NkNxYuKBhXv0ay7D5cSnZsbiE7Vs+Q/qFI7YY/QHZOHiY7B/kBWb5Cdj5+IOlJspul/qTKNiaQvee2kDUlOAH43/3E9EOyG+h+mnu9P320R46In5Ml+/eln9gPrbZcXyLiUbIbOS8iSw5fRe/3w2AVPS4927+OrBb0mtTE4W7g1ILb6ve9OoT4riC7bh4i6/Xltop1l5O1A35cUs9nxoeA/0X2T/I59P9ZMtD2i35u7EN2vh4la4ryErL29P2Wn/4J6wB+lPbhDWRt3X+SPsNWAh+KiPsG2AezMUFZ8zIzMzMzM+vhmmQzMzMzswpOks3MzMzMKjhJNjMzMzOr4CTZzMzMzKyCk2QzMzMzswpOks3MzMzMKjhJNjMzMzOr4CTZzMzMzKyCk2QzMzMzswpOks3MzMzMKjhJNmtQkuZLukfSJknnVZk/U1KXpJ9JWi/ptDT9HEnrco/nJR2V5t2cyuyZ95LR3i8zM7MyUETUO4Zepk2bFrNmzap3GGalcfvttz8aEdPz0yRNBH4BnAxsBtYArRGxMbfMMuBnEfF1SYcDN0TErIpyjgC+HxF/lF7fDHwsItYWjc/XrFlv1a7ZsvD1atZbf9frXqMdzEBmzZrF2rWFv5/NxjxJv64y+RhgU0Tcl5a5BjgD2JhbJoAD0vMDgS1VymkFrhlOfL5mzXrr45otBV+vZr31d726uYVZY3oZ8GDu9eY0LW8J8E5Jm4EbgMVVynkH0Fkx7bLU1OKTklSjeM3MzBqKk2SzsasVuDwiZgCnAVdK2n3NS/oT4OmIuDu3zjkRcQTwxvR4V7WCJS2StFbS2q1bt47cHpiZmdWJk2SzxvQQ8PLc6xlpWl4bcC1ARNwKTAam5eYvoKIWOSIeSn+fBK4ma9axh4hYFhHNEdE8fXopm16amZkNi5Nks8a0BniVpNmS9iZLeFdWLPMAcBKApCayJHlrej0BeDu59siS9pI0LT2fBLwZuBszM7NxyEmyWQOKiJ3AB4EbgW7g2ojYIOkCSaenxT4KnCvpTrIa44XxQnc2xwMP9tz4l+wD3ChpPbCOrGb6W6OwO2bWYDo7O5k7dy4TJ05k7ty5dHZW3tpg1vhK17vFWFb0Hqiydctn/RvMvW21PLcRcQPZDXn5aZ/KPd8IHNfHujcDb6iY9nvg6JoFWICvCbPG09nZSXt7O8uXL2fevHmsXr2atrY2AFpbW+sSU70+h21sc03yKIqIPR7VpteDpMIP663oefUH85583IbPNXqNr8DAQMdLukPSTklnVsz7O0kbJHVL+vvR6JGmo6OD5cuX09LSwqRJk2hpaWH58uV0dHSM9Kb75M9hGwmuSTag+n/WkvyBYlZiZazRs8FJAwN9jdzAQJJW5gcGIru/YCHwsYp1/wfZr0VHpkmrgROAm0cy5u7ububNm9dr2rx58+ju7h7JzZqNOtckm5k1qDLW6Nmg7R4YKCKeI7uZ9oz8AhFxf0SsB56vWDfIbsjdm+yegknAb0c64KamJlavXt1r2urVq2lqahrpTZuNKifJZmYDKGuThrLW6DVK862SnNciAwNVlbp27AIeTo8bI2LET357ezttbW10dXWxY8cOurq6aGtro729faQ3bTaq3NzCzKwfZW7S0FOj19LSsntaGWr0GqH5VpnPa1GSXgk0kfWTDnCTpDdGxH9VLLcIWAQwc+bMYW+35/gsXryY7u5umpqa6OjoaJjjZlaUa5LNzPpR5iYNrtEbuhKd1yIDA/XlrcBtEfFURDwF/BtwbOVCIzH4T2trK3fffTe7du3i7rvvdoJsY5Jrks3M+lHWJg3gGr3hKNF53T0wEFlyvAA4u+C6D5D1hX4hILKb9i4ekSjNxiHXJJuZ9aPsNym5Rm9oynJeiwwMJOn1kjYDZwHflLQhrb4CuBe4C7gTuDMi/mVUd8BsDHNNsplZP3qaNFS2XS1DcwsbujKd1wIDA63hhXbH+WV2Ae8b8QDNxiknyWZm/XCThrHJ59XMBuIk2cxsAK2trU6exiCfVzPrj9skm5mZmZlVcE2ymZmZ2Tg1mEF9ytTX+WhwkmxmZmY2TjXC4D/14uYWVnqNMsTtaJM0X9I9kjZJOq/K/JmSuiT9TNJ6Sael6bMk/UHSuvT4Rm6doyXdlcr8e423g2pmZpa4JtlKz//l7knSROBrwMnAZmCNpJURsTG32CfI+lz9uqTDybqYmpXm3RsRR1Up+uvAucBP0vLzyUbxMjMzG1dck2zWmI4BNkXEfRHxHHANcEbFMgEckJ4fCGzpr0BJhwAHRMRtkf0HcgXwltqGbWZm1hicJJs1ppcBD+Zeb07T8pYA70wjdd0ALM7Nm52aYfxQ0htzZW4eoEwzM7NxoVCSXKDt42GS/jO1e7xZ0ow0/ShJt0rakOa9o9Y7YGZ9agUuj4gZwGnAlZImAA8DMyPitcBHgKslHdBPOXuQtEjSWklrt27dWvPAzczM6m3AJDnX9vFU4HCgNbVvzPsCcEVEHAlcAFyYpj8NvDsi5pC1bbxY0kG1Ct5sHHsIeHnu9Yw0La8NuBYgIm4FJgPTIuLZiHgsTb8duBd4dVo/P/RttTJJ6y2LiOaIaJ4+fXoNdsfMzKxcitQkF2n7eDiwKj3v6pkfEb+IiF+m51uARwB/o5oN3xrgVZJmS9obWACsrFjmAeAkAElNZEnyVknT0z+/SHoF8Crgvoh4GHhC0htSrxbvBv55dHbHzMysXIokyUXaPt4JvC09fyuwv6SD8wtIOgbYm6zWysyGISJ2Ah8EbgS6yXqx2CDpAkmnp8U+Cpwr6U6gE1iYbsg7HlgvaR2wAnh/RGxL6/wVcAmwiexadc8WZmY2LtWqC7iPAV+VtBC4hewn2l09M9Nd81cC74mI5ytXlrQIWAQwc+bMGoVkNrZFxA1kN+Tlp30q93wjcFyV9b4HfK+PMtcCc2sbqZmZ2eDVezTAIknygG0fU1OKtwFIejHw5xHxeHp9AHA90B4Rt1XbQEQsA5YBNDc3D3kv630wzczMzKw26j1OQpHmFgO2fZQ0Ld01D3A+cGmavjdwHdlNfStqF3Z1EbHHo7/pZmZm9VSg96jjJd0haaekMyvmzZT0A0ndkjZKmjXCsZZi9NOpU6cWjqHIclOnTh3ReIvGMRrHzgZnwJrkiNgpqaft40Tg0p62j8DaiFgJvAm4UFKQNbf4QFr97WTtHw9OTTEgaxe5rra7YWZm1lgKjpz5ALCQrFljpSuAjoi4Kf2Ku0dzxlqqd61ej+3bt9d0m6ORmJbl2NngFGqTXKDt4wqyG4Aq17sKuGqYMZqZmY1Fu3uPApDU03vU7iQ5Iu5P83olwKkr1r0i4qa03FOjFLPZuOER98zMzOqjSO9RfXk18Likf0qjZ/6/nq4dzaw2nCSbmZk1nr2AN5I1w3g98AqyZhl78AiZZkPjJNnMzKw+ioyc2ZfNwLo00NdO4PvA66ot6BEyzYbGSbKZWYPxnfJjRpGRM/tb9yBJPVnvieTaMpvZ8DlJNjNrMO7ucmwoMnKmpNdL2gycBXxT0oa07i6yphb/KekuQMC36rEfZmNVrUbcMzMzs0Eq0HvUGrJmGNXWvQk4ckQDNBvHnCSbmdm44ZFZzawoJ8lmZlU4mRqbPKiDmRXlJNnMrAonU2blFJ8+AJYcWNvyamjq1Kls37690LID/TM+ZcoUtm3bVouwgNrGBvWLb7Ric5JsZmZmvZQ5mdJnnqj5sNSxpGbF1XTY7Fr3UFP2Ib3Lduzcu4VZg5I0X9I9kjZJOq/K/JmSutJoXOslnZamnyzpdkl3pb8n5ta5OZW5Lj1eMpr7ZGbl0JOs1OpRNOE2KxPXJJs1oDT87NeAk8kGFVgjaWVE5PtJ/QRZl1Jfl3Q42R30s4BHgf8VEVskzSXrfio/FO45EbF2NPbDzMysrFyTbNaYjgE2pdG2ngOuAc6oWCaAnsZ2BwJbACLiZxGxJU3fAOwraZ9RiNnMzKxhOEk2a0wvAx7Mvd5M79pggCXAO9NABDcAi6uU8+fAHRHxbG7aZampxSflIdvMzGyccnMLs7GrFbg8Ir4o6VjgSklzI+J5AElzgM8Dp+TWOSciHpK0P/A94F3AFZUFS1oELAKYOXPmCO+GmZmNB7XsuaQWvZY4STZrTA8BL8+9npGm5bUB8wEi4lZJk4FpwCOSZgDXAe+OiHt7VoiIh9LfJyVdTdasY48kOSKWAcsAmpub3SeamZkNWy17LqlFryVubmHWmNYAr5I0W9LewAJgZcUyDwAnAUhqAiYDWyUdBFwPnBcRP+pZWNJekqal55OANwN3j/iemJmZlZCTZLMGFBE7gQ+S9UzRTdaLxQZJF0g6PS32UeBcSXcCncDCyP5F/yDwSuBTFV297QPcKGk9sI6sZvpbo7tnZmZm5eDmFmYNKiJuILshLz/tU7nnG4Hjqqz3OeBzfRR7dC1jNDMza1ROks3MzKyXsg/9bDYanCSbmZnVkaT5wFeAicAlEXFRxfzjgYuBI4EFEbGiYv4BwEbg+xHxwZrEVPKhn81Gg9skm5mZ1Ulu9MxTgcOB1jRCZt4DwELg6j6K+Sxwy0jFaDZeOUk2MzOrnwFHz4yI+yNiPfB85cqSjgZeCvxgNII1G0+cJJuZmdVPkdEzq5I0Afgi8LERiMts3HOSbGZm1pj+CrghIjb3t5CkRZLWSlq7devWUQrNrPH5xj0zM7P6KTJ6Zl+OBd4o6a+AFwN7S3oqIs7LL+QRMs2GxkmymZlZ/ewePZMsOV4AnF1kxYg4p+e5pIVAc2WCbGZDV6i5haT5ku6RtEnSHhegpMMk/aek9ZJuljQjN+89kn6ZHu+pZfBmZmaNrMjomZJeL2kzcBbwTUkb6hex2fgxYE1yrnuak8luKFgjaWUazavHF4ArIuLbkk4ELgTeJWkq8GmgGQjg9rTu9lrviJmZWSMqMHrmGrJmGP2VcTlweS3jklSzsqZMmVKzssxGS5Ga5AG7pyHr23FVet6Vm/9nwE0RsS0lxjcB84cftpmZlcHUqVORNOADGHCZqVOn1nlvrEdEFHoUXXbbtm113iOzwSvSJrla9zR/UrHMncDbyEYMeiuwv6SD+1i3UNc2ZmZWftu3b6/ZyGy1rLk0q5daDuld6+G8Pdz44NTqxr2PAV9NNw7cQnbzwa6iK0taBCwCmDlzZo1CMjMzMxtdtRzSu9bDeXu48cEp0txiwO5pImJLRLwtIl4LtKdpjxdZNy27LCKaI6J5+vTpg9wFM2sERX6Wh4F/kvfP8mZmNhqKJMm7u6eRtDdZ9zQr8wtImpZG/gE4H7g0Pb8ROEXSFElTgFPStGGrZTu48fal62M3NhTodWampC5JP0s9z5yWm3d+Wu8eSX9WtMzh6PlZvhaP7dt976+ZmY2sAZtbRMROST3d00wELu3pngZYGxErgTcBF0oKsuYWH0jrbpP0WbJEG+CCiKhJ6/1atoOD8dUWzseu8RXsdeYTZN1JfV3S4WR3z89KzxcAc4BDgf+Q9Oq0zkBlmpmZjQuF2iQX6J5mBbCij3Uv5YWaZTOrjd29zgBI6ul1Jp/QBtBzV8WBwJb0/Azgmoh4FviVpE2pPAqUaWZmNi4UGkzEbLS4KUhhRXqOWQK8U9kgBDcAiwdYd9z2RlPm912ZYys7HzszGw4PSz1Cpk6dWrjd5EDNFaZMmTJu+pgse1OQWp5XGPFz2wpcHhFflHQscKWkubUoWGOsR5oyv+/KHFvZ+diZ2XA4SR4h7jt0bCrRl26RnmPaSIP3RMStkiYD0wZYd8DeaFJ5y4BlAM3NzbU7IGZmZiXh5hZmjWnAXmeAB4CTACQ1AZOBrWm5BZL2kTQbeBXw04JlmpnVXZHmMUUf423I7LIfuzLF5ppkswZUsNeZjwLfkvRhspv4FkZWDb5B0rVkN+TtBD4QEbsAqpU56jtnZtaPor/mSarpL39jQdmPXZFtjmZsTpLNGlSBXmc2Asf1sW4H0FGkTDMzs/HISbKZmZkNqK97KKpNH+81uLW6l2i8NQWpVO/3XMMmyfHpA2DJgbUtz8zMzKoa74lvUWVv0tBI6n18GjZJ1meeqHkvA7GkZsWZmZkNSNJ84Ctk9wFcEhEXVcw/HrgYOBJYkAbvQtJRwNfJBgzaBXRExHdHM3azsc69W5iZmdWBXhhe/lTgcKBV2bDxeQ8AC4GrK6Y/Dbw7IuaQdfV4saSDRjZis/GlYWuSzczMGtyAw8tHxP1p3vP5FSPiF7nnWyQ9AkwHHh/5sM3GB9ckm5mZ1UdNhoKXdAywN3BvjeIyM5wkm5mZNSxJhwBXAu+NiOf7WGaRpLWS1m7dunV0AzRrYE6SzczM6qPI8PJ9knQAcD3QHhG39bVcRCyLiOaIaJ4+ffqQgzUbb5wkm5mZ1ceQh4JPy18HXNHT44WZ1ZaTZDMzszqIiJ1Az1Dw3cC1PcPLSzodQNLrJW0GzgK+KalnqPi3A8cDCyWtS4+j6rAbZmOWe7cwM7Mhq+XATuNxUKcCw8uvIWuGUbneVcBVIx6g2TjmJNnMzIaslgM7eVAnMysTN7cwMzMzM6vgmmQzGxX+Wd7MzBqJk2QrlVomUrvLs1Io88/yZX7flTm2svOxM7PhUK2+tGqlubk51q5dO+Bykmr2hTsS5dXygzkr73c1K6rMx67MsQG1P68w4LmVdHtENFeZPh/4CjARuCQiLqqY/2WgJb18EfCSiDhIUgvw5dyirwEWRMT3JV0OnAD0BLUwItb1F189rtmyv0+8r/Uvq57l9XXNlkHR63UsqPnnf42VOb4yx1Zr/V2vrkkeIa41G5tqeV5h6OdW0kTga8DJZEPZrpG0MiI29iwTER/OLb8YeG2a3gUclaZPBTYBP8gV/9fud9XMzMY7J8njUFkSPRuWY4BNEXEfgKRrgDOAjX0s3wp8usr0M4F/i4inRyRKMzOzBuXeLcwa08uAB3OvN6dpe5B0GDAbWFVl9gKgs2Jah6T1kr4saZ9aBGtmZtZonCSbjX0LgBURsSs/UdIhwBFko331OJ+sjfLrganAx6sVKGmRpLWS1m7dunVkojaz0urs7GTu3LlMnDiRuXPn0tlZ+b+2WeNzkmzWmB4CXp57PSNNq6ZabTFkw9peFxE7eiZExMOReRa4jKxZxx4iYllENEdE8/Tp04e0A2bWmDo7O2lvb2fp0qU888wzLF26lPb2difKNuYUSpIlzZd0j6RNks6rMn+mpC5JP0s/056Wpk+S9G1Jd0nqlnR+rXfAbJxaA7xK0mxJe5MlwisrF5L0GmAKcGuVMlqpSJ5T7TKSBLwFuLvGcXUqStUAABGoSURBVJtZg+vo6GD58uW0tLQwadIkWlpaWL58OR0dHfUOzaymBkySc3fRnwocDrRKOrxisU8A10bEa8m+rP8hTT8L2CcijgCOBt4naVZtQjcbvyJiJ/BBsqYS3WTX3wZJF0g6PbfoAuCaqLhTM12HLwd+WFH0dyTdBdwFTAM+NzJ7YGaNqru7m3nz5vWaNm/ePLq7u+sUkdnIKNK7RZG76APo6QfsQGBLbvp+kvYC9gWeA56oQdxm415E3ADcUDHtUxWvl/Sx7v1UudEvIk6sXYRWK1nFfm1MmTKlZmXZ+NTU1MTq1atpaWnZPW316tU0NTXVMSqz2ivS3KLIXfRLgHdK2kz2pb04TV8B/B54GHgA+EJEbBtOwHmSavbwF4fZ+FbWz5OIKPQouuy2bTX7CG4IZT2vjay9vZ22tja6urrYsWMHXV1dtLW10d7eXu/QzGqqVv0ktwKXR8QXJR0LXClpLlkt9C7gULJ2kf8l6T96aqV7SFoELAKYOXNmoQ0W7ed3PI0aY2ZD48+TsalRzqsGHj3zeOBi4Eiy0TFX5Oa9h6zJI8DnIuLbIx1va2srAIsXL6a7u5umpiY6Ojp2TzcbK4okyUXuom8D5gNExK2SJpO1Zzwb+Pd09/wjkn4ENAO9kuSIWAYsg2zIzCHsh5mZWcMpMnom2S+xC4GPVaw7lWyQoGay5o23p3W3j3Tcra2tToptzCvS3KLIXfQPACcBSGoCJgNb0/QT0/T9gDcAP69N6GZmZg1v930/EfEc0HPfz24RcX9ErAeer1j3z4CbImJbSoxvIlVYmdnwDZgkF7yL/qPAuZLuJOtSamG6m/5rwIslbSBLti9LF7qZmZkNYvTMGq9rZgMo1CZ5oLvo089Cx1VZ7ymybuDMzMysDoZy34+ZecQ9MzOzehrM6JlDWtcjZJoNjZNkMzOz+ik0emYfbgROkTRF0hTglDTNzGrASbKVjvs1NbPxosh9P5Jen8YhOAv4ZrrPhzTuwGfJEu01wAW1HIvAbLyrVT/J1mDKOoJXo/RramZWKwXu+1lD1pSi2rqXApeOaIA2bH1951abPtrfbWWOrd6cJI9DTkTNzMxGT5m/S8scW725uYWZmZmZWQUnyWZmZmZmFZwkm5mZmZlVcJJsNkhl6X1D0nxJ90jaJOm8KvO/LGldevxC0uO5ebty81bmps+W9JNU5ndTl1RmZmbjjm/cG0G16kHC3ZiVR1luepQ0kWzY95PJhqJdI2llGv0SgIj4cG75xcBrc0X8ISKOqlL054EvR8Q1kr4BtAFfH4l9MDMzKzPXJI+QiCj0KLLstm3u9tL2cAywKSLui4jngGuAM/pZvhXo7K9AZf/VnQisSJO+DbylBrHaGFeGX1bMzGrNNclmjellwIO515uBP6m2oKTDgNnAqtzkyZLWAjuBiyLi+8DBwONpcIOeMl9W68BtbCnLrytmZrXmmmSzsW8BsCIiduWmHRYRzcDZwMWS/mgwBUpaJGmtpLVbt26tZaxmZlYnnZ2dzJ07l4kTJzJ37lw6O/v9AXLMc5Js1pgeAl6eez0jTatmARVNLSLiofT3PuBmsvbKjwEHSer5hanPMiNiWUQ0R0Tz9OnTh7oPZmZWEp2dnbS3t7N06VKeeeYZli5dSnt7+7hOlJ0kmzWmNcCrUm8Ue5MlwisrF5L0GmAKcGtu2hRJ+6Tn04DjgI2R/RbeBZyZFn0P8M8juhdmZlYKHR0dLF++nJaWFiZNmkRLSwvLly+no6Oj3qHVjZNkswaU2g1/ELgR6AaujYgNki6QdHpu0QXANdG7MWgTsFbSnWRJ8UW5XjE+DnxE0iayNsrLR3pfzMys/rq7u5k3b16vafPmzaO7u7tOEdWfb9wza1ARcQNwQ8W0T1W8XlJlvR8DR/RR5n1kPWeYmdk40tTUxOrVq2lpadk9bfXq1TQ1NdUxqvpyTbKZmZnZONfe3k5bWxtdXV3s2LGDrq4u2traaG9vr3dodeOaZDMzszqSNB/4CjARuCQiLqqYvw9wBXA02Q2274iI+yVNAi4BXkf2fX5FRFw4qsHbmNHa2grA4sWL6e7upqmpiY6Ojt3TxyMnyWZmZnVSZPRMspEvt0fEKyUtIBsZ8x3AWcA+EXGEpBcBGyV1RsT9o7sXNla0traO66S4kptbmJlVUW1EuP6mW2Mo4XktMnrmGWQjYEI2IuZJaYTMAPZL3TbuCzwHPDE6YZuNfU6SzcyqKDq0vEeRaywlPK/VRs+sHOly9zKpZ5vfkfU+swL4PfAw8ADwhYjYNtIBm40XTpLNzMwa0zHALuBQsqHnPyrpFZULeYRMs6Fxkmxm1mBK2GTAhq7I6Jm7l0lNKw4ku4HvbODfI2JHRDwC/AhortyAR8g0GxonyWY2aqolcUN5TJkypd67UlclbDJgQ1dk9MyVZCNgQjYi5qo0QNADwIkAkvYD3gD8fFSiNhsH3LuFmY2KIgmbJCd2Nq5ExE5JPaNnTgQu7Rk9E1gbESvJRr68Mo2EuY0skYasV4zLJG0ABFwWEetHfy/MxiYnyWZmZnU00OiZEfEMWXdvles9VW36eNRX06Jq0/2PuBVVqLmFpPmS7pG0SdJ5VebPlNQl6WeS1ks6LTfvSEm3Stog6S5Jk2u5A2ZmZja+uQmSjYQBa5ILdnT+CeDaiPi6pMPJ/iOelW4wuAp4V0TcKelgYEfN98LMzMzMrIaK1CQX6eg8gAPS8wOBLen5KcD6iLgTICIei4hdww/bzMzMzGzkFEmSi3R0vgR4p6TNZLXIi9P0VwMh6UZJd0j6m2HGa2ZmZmY24mrVBVwrcHlEzABOI7sLdwJZc455wDnp71slnVS5sjs6Nxu8AvcKfFnSuvT4haTH0/SjcvcJrJf0jtw6l0v6VW69o0Zzn8zMzMqiSO8WRTo6bwPmA0TErenmvGlktc63RMSjAJJuAF4H/Gd+5YhYBiwDaG5uHnKret/dauNFkXsFIuLDueUXA69NL58G3h0Rv5R0KHC7pBsj4vE0/68jYsWo7IiZmVlJFalJLtLR+QPASQCSmoDJwFayfh+PkPSidBPfCcBGRojvbrVxpMi9AnmtQCdARPwiIn6Znm8BHgE8DJeZmVnOgElyROwEejo67ybrxWKDpAsknZ4W+yhwrqQ7yb6IF0ZmO/AlskR7HXBHRFw/EjtiNs4UuVcAAEmHAbOBVVXmHQPsDdybm9yRmmF8WdI+tQvZzMyscRQaTKRAR+cbgeP6WPcqsm7gzKw+FgArKnuWkXQIcCXwnoh4Pk0+H/gNWeK8DPg4cEFlgZIWAYsAZs6cOXKRW0Ny0zczGwtqdeOemY2uIvcK9FhAamrRQ9IBwPVAe0Tc1jM9Ih5OvwI9C1xG1qxjDxGxLCKaI6J5+nS31LDe3PTNzMYCJ8lWepL2ePQ3fZwocq8Akl4DTAFuzU3bG7gOuKLyBr1Uu4yyg/kW4O4R2wMzM7MSK9TcwqyeXNu0p4jYKannXoGJwKU99woAayOiJ2FeAFwTvQ/i24HjgYMlLUzTFkbEOuA7kqYDIruP4P2jsDtmZmal4yTZrEENdK9Aer2kynp93icQESfWMEQzM7OG5eYWZmZmZmYVnCSbmZmZmVVwkmxmdeMbMs0KDTG/j6Tvpvk/kTQrN+/I3DDzd6URb82sBsZsktzZ2cncuXOZOHEic+fOpbOzc+CVzGxUuZswG+9yQ8yfChwOtEo6vGKxNmB7RLwS+DLw+bTuXmT3F7w/IuYAbwJ2jFLoZmPemEySOzs7aW9vZ+nSpTzzzDMsXbqU9vZ2J8pmNua4QqDhFRli/gzg2+n5CuCk1E3jKcD6iLgTICIeqxw0yMyGbkwmyR0dHSxfvpyWlhYmTZpES0sLy5cvp6Ojo96hmVkDKmsi6gqB4SnJeS0yxPzuZSJiJ/A74GDg1UBIulHSHZL+ZhTiNauLulyvgxkZaTQeRx99dAzXhAkT4rnnnus17bnnnosJEyYMu+xay05BOZU5trKr5bEj6/e47tdmX49aXLNldvXVV8fs2bNj1apV8dxzz8WqVati9uzZcfXVV9c7tJgzZ06sWrWq17RVq1bFnDlz6hRR4xjJ8zqYaxY4E7gk9/pdwFcrlrkbmJF7fS8wDfgY8Kv0/EVkgwadVGUbi4C1wNqZM2cOe//MRlu9rte6f8FWPmrxhdtIXxxlTkTLHFvZOUkeO8r8edJIFQJlM5LndZBJ8rHAjbnX5wPnVyxzI3Bser4X8CjZgD8LgG/nlvsk8Nf9bW+sX682NtXreh2TzS3a29tpa2ujq6uLHTt20NXVRVtbG+3t7XWNq+jwymWOzT0N7MnHbmzr7u5m3rx5vabNmzeP7u7uOkX0gqamJlavXt1r2urVq2lqaqpTRI2jROe1yBDzK4H3pOdnAqvSl/uNwBGSXpRu4jsB2DhKcZuNmnpdr2MySW5tbaWjo4PFixczefJkFi9eTEdHB62trXWNq6//VCofZY6tXvGVmY/d2FbmRLSsFQKNoCznNbI2xj1DzHcD10YaYl7S6Wmx5WTDyG8CPgKcl9bdDnyJLNFeB9wREdeP6g6YjYK6Xa+D+YIfjYd/CjLrDTe3qKsyt0mOyOKbM2dOTJgwIebMmVOauMquLG2SR/sx1q9XG5vqdb3uNbIpuJlZY+v5BWrx4sV0d3fT1NRUil+merS2tpYmlkZS9vNqZi+o1/WqKNlPwM3NzbF27dp6h2FWGpJuj4jmesfRF1+zZr2V+Zr19WrWW3/X65hsk2xmZmZmNhxOks3MzMzMKjhJNjMzMzOrULo2yZK2Ar+uYZHTyDpeL6syx+fYhq6W8R0WEdNrVFbN1fiaHU/ntdbKHBuUO75ax1baa3acfceWOTYod3zjKbY+r9fSJcm1JmltWW+ggHLH59iGruzxlVXZj1uZ4ytzbFDu+MocW9mV+diVOTYod3yOLePmFmZmZmZmFZwkm5mZmZlVGA9J8rJ6BzCAMsfn2Iau7PGVVdmPW5njK3NsUO74yhxb2ZX52JU5Nih3fI6NcdAm2czMzMxssMZDTbKZmZmZ2aCM2SRZ0qWSHpF0d71jqSTp5ZK6JG2UtEHSh+odU56kyZJ+KunOFN9n6h1TJUkTJf1M0r/WO5Y8SfdLukvSOkke+7UgX69D5+t1eHzNDo2v2aHx9To8o329jtnmFpKOB54CroiIufWOJ0/SIcAhEXGHpP2B24G3RMTGOocGgCQB+0XEU5ImAauBD0XEbXUObTdJHwGagQMi4s31jqeHpPuB5ogoa/+SpeTrdeh8vQ6Pr9mh8TU7NL5eh2e0r9cxW5McEbcA2+odRzUR8XBE3JGePwl0Ay+rb1QviMxT6eWk9CjNf1OSZgD/E7ik3rFYbfh6HTpfr1YPvmaHxtdrYxmzSXKjkDQLeC3wk/pG0lv6uWUd8AhwU0SUKb6Lgb8Bnq93IFUE8ANJt0taVO9grLZ8vQ5Jma9X8DU7ppXxmvX1Oiyjer06Sa4jSS8Gvgf834h4ot7x5EXErog4CpgBHCOpFD+nSXoz8EhE3F7vWPowLyJeB5wKfCD9JGljgK/XwWuA6xV8zY5ZZb1mfb0Oy6her06S6yS1Rfoe8J2I+Kd6x9OXiHgc6ALm1zuW5Djg9NQu6RrgRElX1TekF0TEQ+nvI8B1wDH1jchqwdfrkJX6egVfs2NVI1yzvl4Hb7SvVyfJdZAa7i8HuiPiS/WOp5Kk6ZIOSs/3BU4Gfl7fqDIRcX5EzIiIWcACYFVEvLPOYQEgab90kwiS9gNOAUp357cNjq/XoSvz9Qq+ZseqMl+zvl6Hrh7X65hNkiV1ArcCfyxps6S2eseUcxzwLrL/0talx2n1DirnEKBL0npgDVmbqdJ1BVNCLwVWS7oT+ClwfUT8e51jagi+XofF1+vQ+ZodIl+zQ+brdehG/Xods13AmZmZmZkN1ZitSTYzMzMzGyonyWZmZmZmFZwkm5mZmZlVcJJsZmZmZlbBSbKZmZmZWQUnyWZmZmZmFZwkm5mZmZlVcJJsZmZmZlbh/wMRFpE8n54r/QAAAABJRU5ErkJggg==\n",
            "text/plain": [
              "<Figure size 864x216 with 3 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Model validation: find regularization type and rate\n",
        "from scipy.stats import loguniform\n",
        "from sklearn.linear_model import LogisticRegression\n",
        "from sklearn.model_selection import RepeatedStratifiedKFold\n",
        "from sklearn.model_selection import RandomizedSearchCV\n",
        "\n",
        "def validate_model(X,y):\n",
        "  model = LogisticRegression()\n",
        "  cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)\n",
        "  space = dict()\n",
        "  space['solver'] = ['liblinear']\n",
        "  space['penalty'] = ['none', 'l1', 'l2', 'elasticnet']\n",
        "  space['C'] = loguniform(1e-5, 100)\n",
        "\n",
        "  search = RandomizedSearchCV(model, space, n_iter=500, scoring='roc_auc', n_jobs=-1, cv=cv, random_state=1)\n",
        "  res = search.fit(X, y)\n",
        "\n",
        "  print('Score: %s' % res.best_score_)\n",
        "  print('Hyperparameters: %s' % res.best_params_)\n",
        "  return res.best_params_\n",
        "\n",
        "# insert input variables (list of features) to validate the model\n",
        "features = ['Total words', 'Age Co-Lead', 'Number of female actors', 'Difference in words lead and co-lead', 'Number of words lead', 'Age Lead', 'Number words female', 'Number of male actors']\n",
        "validate_model(X[features], y)"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "gE30zGQUPgb8",
        "outputId": "b749a19b-2eb4-4051-b456-f56ecf14aef9"
      },
      "execution_count": 9,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Score: 0.8824215081683437\n",
            "Hyperparameters: {'C': 11.255272403301097, 'penalty': 'l1', 'solver': 'liblinear'}\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning: \n",
            "7590 fits failed out of a total of 15000.\n",
            "The score on these train-test partitions for these parameters will be set to nan.\n",
            "If these failures are not expected, you can try to debug them by setting error_score='raise'.\n",
            "\n",
            "Below are more details about the failures:\n",
            "--------------------------------------------------------------------------------\n",
            "3720 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py\", line 1461, in fit\n",
            "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py\", line 464, in _check_solver\n",
            "    raise ValueError(\"penalty='none' is not supported for the liblinear solver\")\n",
            "ValueError: penalty='none' is not supported for the liblinear solver\n",
            "\n",
            "--------------------------------------------------------------------------------\n",
            "3870 fits failed with the following error:\n",
            "Traceback (most recent call last):\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_validation.py\", line 680, in _fit_and_score\n",
            "    estimator.fit(X_train, y_train, **fit_params)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py\", line 1461, in fit\n",
            "    solver = _check_solver(self.solver, self.penalty, self.dual)\n",
            "  File \"/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py\", line 459, in _check_solver\n",
            "    solver\n",
            "ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.\n",
            "\n",
            "  warnings.warn(some_fits_failed_message, FitFailedWarning)\n",
            "/usr/local/lib/python3.7/dist-packages/sklearn/model_selection/_search.py:972: UserWarning: One or more of the test scores are non-finite: [       nan 0.8823882         nan 0.68771851 0.6825994  0.88129627\n",
            " 0.87853394        nan 0.79960189 0.8105241         nan 0.87463987\n",
            "        nan 0.88202395        nan 0.62885738        nan        nan\n",
            "        nan        nan        nan 0.88132806        nan        nan\n",
            "        nan        nan        nan 0.88119433        nan 0.68669472\n",
            " 0.87287889 0.76544047        nan 0.8791939         nan 0.87898012\n",
            "        nan        nan 0.77980159        nan        nan 0.88233889\n",
            "        nan 0.8794161  0.8790216         nan        nan        nan\n",
            "        nan        nan        nan        nan 0.88182538        nan\n",
            " 0.87987328        nan        nan        nan 0.8789734  0.87750332\n",
            "        nan 0.75243742 0.87877181 0.8692985         nan 0.72249311\n",
            "        nan 0.87862647 0.88233779 0.8765889         nan        nan\n",
            "        nan        nan 0.77728548        nan 0.618294          nan\n",
            " 0.88237132 0.87897825 0.60121286        nan 0.69425893 0.71862927\n",
            " 0.87930456        nan        nan 0.87862185 0.879488          nan\n",
            " 0.68753264        nan        nan        nan        nan        nan\n",
            "        nan 0.88207414 0.88160773        nan 0.75529345        nan\n",
            " 0.79901494        nan 0.79548368 0.76361849        nan        nan\n",
            "        nan        nan 0.73406586 0.61014464 0.87953618 0.87698236\n",
            "        nan 0.67252639        nan 0.88235466 0.70979823 0.8796487\n",
            " 0.8805249  0.76507094 0.75297572 0.63089831 0.79531492        nan\n",
            "        nan 0.85361783        nan 0.88170834        nan        nan\n",
            "        nan 0.87232586 0.87933919 0.59347182 0.87058372        nan\n",
            "        nan        nan 0.87097955        nan        nan 0.87931596\n",
            " 0.60226264 0.88237221        nan        nan        nan        nan\n",
            " 0.87884498        nan 0.87954038 0.8791884  0.87842329        nan\n",
            " 0.87822454 0.85049544        nan        nan 0.74141006 0.88228913\n",
            "        nan 0.87912554        nan 0.74700633        nan 0.88240441\n",
            " 0.77663687 0.62334165        nan 0.8736569  0.71862623        nan\n",
            " 0.88238798        nan 0.88242151        nan 0.87669435        nan\n",
            " 0.8724563  0.77521931        nan 0.86237311        nan        nan\n",
            "        nan        nan 0.87865322 0.73322816 0.87905278        nan\n",
            "        nan 0.74496343 0.88190757        nan        nan 0.88192511\n",
            " 0.75853176        nan 0.87906372        nan        nan 0.87924564\n",
            " 0.75919223 0.88232201 0.84988434 0.87949           nan 0.87057477\n",
            "        nan        nan        nan 0.74874631        nan        nan\n",
            "        nan        nan 0.87932514 0.78249323        nan        nan\n",
            "        nan        nan        nan 0.62280269        nan 0.87926032\n",
            " 0.8785745  0.85326878 0.87971227 0.88175876        nan        nan\n",
            "        nan 0.73990519        nan 0.87879911 0.87224438        nan\n",
            "        nan        nan 0.87952243 0.87810039        nan        nan\n",
            "        nan        nan        nan 0.88235445 0.86594787 0.87871459\n",
            "        nan        nan        nan 0.87799705        nan 0.88111233\n",
            " 0.87467318        nan 0.80275755 0.72412293 0.73775669 0.76227431\n",
            " 0.79426914        nan        nan        nan        nan 0.7757381\n",
            " 0.8792439  0.87888008        nan 0.76129126 0.87822906        nan\n",
            "        nan        nan        nan 0.87873107        nan 0.87849717\n",
            "        nan 0.87832866 0.60594953        nan 0.88175831 0.88238953\n",
            "        nan 0.62507032        nan 0.8793146         nan 0.87876479\n",
            "        nan        nan 0.88235577        nan 0.88237088 0.62208604\n",
            " 0.79285624 0.87924014 0.88238887 0.88174099 0.87907116 0.87900498\n",
            "        nan        nan 0.67286086 0.88107771        nan        nan\n",
            "        nan 0.88192445 0.8666082         nan        nan        nan\n",
            " 0.87921624        nan 0.85461403        nan        nan        nan\n",
            " 0.7188984  0.8823711  0.84983724 0.87919587 0.86515784        nan\n",
            " 0.88237132        nan 0.87892322 0.77435183        nan 0.67465285\n",
            " 0.87948533        nan        nan        nan 0.87950466 0.87226829\n",
            "        nan        nan        nan        nan 0.87921642 0.87658656\n",
            " 0.88235533        nan 0.60760382 0.79514725        nan        nan\n",
            "        nan 0.87422888 0.8822727         nan 0.87725579 0.88232224\n",
            "        nan        nan 0.87462387        nan        nan        nan\n",
            " 0.6865757  0.87897888 0.87959145 0.88237066        nan        nan\n",
            " 0.88190757 0.83610134        nan 0.87329222        nan        nan\n",
            "        nan        nan        nan 0.87953907 0.88111125 0.87956364\n",
            "        nan 0.88230689 0.8625317  0.73039082 0.87895037 0.87955393\n",
            " 0.87527518 0.7908858         nan        nan 0.88169146 0.78499636\n",
            "        nan        nan        nan        nan        nan 0.87928501\n",
            "        nan        nan 0.87888509        nan 0.88227072 0.87961969\n",
            " 0.87900498        nan 0.88237221 0.85077924        nan 0.87234454\n",
            " 0.87831451        nan        nan        nan        nan        nan\n",
            " 0.84273434 0.76098768 0.87501996 0.75697064        nan 0.87721682\n",
            "        nan 0.62146798        nan 0.87272766        nan 0.87904047\n",
            " 0.87742916        nan        nan 0.87950332        nan 0.88233868\n",
            "        nan 0.61925875        nan 0.81267645 0.87814189 0.87794439\n",
            "        nan        nan        nan        nan 0.87274359        nan\n",
            " 0.87998636 0.85831253        nan 0.68741383        nan        nan\n",
            "        nan        nan        nan        nan 0.72738467 0.86477558\n",
            "        nan        nan 0.72328679 0.78982201        nan        nan\n",
            " 0.87958527 0.61036184        nan 0.87958836 0.85991444 0.70745727\n",
            "        nan 0.84846895        nan 0.87615625        nan 0.87903541\n",
            "        nan        nan 0.87979773 0.8783963         nan        nan\n",
            " 0.88233845        nan        nan 0.87906917        nan        nan\n",
            "        nan        nan 0.62205295        nan        nan        nan\n",
            "        nan        nan]\n",
            "  category=UserWarning,\n"
          ]
        },
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "{'C': 11.255272403301097, 'penalty': 'l1', 'solver': 'liblinear'}"
            ]
          },
          "metadata": {},
          "execution_count": 9
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Find threshold rate for the best model (result = 0.435)\n",
        "features = ['Total words', 'Age Co-Lead', 'Number of female actors', 'Difference in words lead and co-lead', 'Number of words lead', 'Age Lead', 'Number words female', 'Number of male actors']\n",
        "# parameters {'C': 18.31792545756584, 'penalty': 'l1', 'solver': 'liblinear'}\n",
        "\n",
        "n_runs = 10\n",
        "tr_rates_n = np.zeros((n_runs))\n",
        "X = data[features]\n",
        "y = data['Lead']\n",
        "\n",
        "for i in range(n_runs):\n",
        "\n",
        "  X_train, X_val, y_train, y_val = skl_ms.train_test_split(X, y, test_size = 0.3)\n",
        "\n",
        "  model = skl_lm.LogisticRegression(solver ='liblinear', C = 18.31792545756584, penalty ='l1')\n",
        "  scaler = skl_pre.StandardScaler().fit(X_train)\n",
        "  model.fit(scaler.transform(X_train), y_train)\n",
        "  predict_prob = model.predict_proba(scaler.transform(X_val))\n",
        "  tr_rates_n[i] = find_r(predict_prob, y_val)\n",
        "\n",
        "r_res = np.average(tr_rates_n)\n",
        "print(r_res)\n",
        "\n"
      ],
      "metadata": {
        "id": "Paxn7HoZU_7_",
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "outputId": "739dd14f-2374-4c2f-91f0-123992cea59c"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "0.42600000000000005\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n",
            "/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:21: RuntimeWarning: invalid value encountered in long_scalars\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "# Evaluate performance of logistic regression model\n",
        "pc_auc_n2 =np.zeros((n_runs))\n",
        "roc_auc_n2 = np.zeros((n_runs))\n",
        "misclassification_n2 = np.zeros((n_runs))\n",
        "\n",
        "\n",
        "n_fold = 10\n",
        "cv = skl_ms.KFold(n_splits = n_fold, random_state = 1, shuffle = True)\n",
        "\n",
        "for i, (train_index, val_index) in enumerate(cv.split(X)):\n",
        "  X_train, X_val = X.iloc[train_index], X.iloc[val_index]\n",
        "  y_train, y_val = y.iloc[train_index], y.iloc[val_index]\n",
        "\n",
        "  model = skl_lm.LogisticRegression(solver ='liblinear', C = 18.31792545756584, penalty ='l1')\n",
        "\n",
        "  scaler = skl_pre.StandardScaler().fit(X_train)\n",
        "  model.fit(scaler.transform(X_train[features]), y_train)\n",
        "  predict_prob = model.predict_proba(scaler.transform(X_val))\n",
        "  # calculate the metrics\n",
        "  precision, recall, _ = precision_recall_curve(y_val, predict_prob[:,1])\n",
        "\n",
        "  pc_auc_n2[i] = auc(recall, precision)\n",
        "  roc_auc_n2[i] = roc_auc_score(y_val, predict_prob[:,1])  \n",
        "\n",
        "\n",
        "  tr_rate = 0.435\n",
        "  prediction = np.where(predict_prob[:,1] > tr_rate, 1, 0)\n",
        "  misclassification_n2[i] = (np.mean(prediction != y_val))\n",
        "\n",
        "print('ROC AUC', np.average(roc_auc_n2))\n",
        "print('PC AUC', np.average(pc_auc_n2))\n",
        "print('Error', np.average(misclassification_n2))\n",
        "\n",
        "fig, axs = plt.subplots(1, 3, figsize=(12, 3), sharey=False)\n",
        "axs[0].boxplot(roc_auc_n2)\n",
        "axs[1].boxplot(pc_auc_n2)\n",
        "axs[2].boxplot(misclassification_n2)\n",
        "\n",
        "axs[0].set_xticks(range(1))\n",
        "axs[1].set_xticks(range(1))\n",
        "axs[2].set_xticks(range(1))\n",
        "#axs[0].set_xticklabels([str('ROC AUC')+\"foo\" for x in range(1)])\n",
        "#axes.set_xticklabels(labels, fontdict=None, minor=False)\n",
        "\n",
        "fig.suptitle('Evaluation of log regression model (ROC AUC, PC AUC, misclassification error)')\n",
        "plt.show()\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 271
        },
        "id": "DCQpsW_mkE54",
        "outputId": "460b6051-1d57-4f80-f4f2-c49c4aa751ae"
      },
      "execution_count": 11,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "ROC AUC 0.8876033271155791\n",
            "PC AUC 0.7929100050122352\n",
            "Error 0.13285100821508586\n"
          ]
        },
        {
          "output_type": "display_data",
          "data": {
            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAskAAADKCAYAAABXPt1qAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliLm9yZy+WH4yJAAAgAElEQVR4nO3df7xVVZ3/8ddbBDEV5FelooCTfQPR0cQfTebvSpnSarIgS3GYrCn5zpRWOpiRST9m+mHj2A9NJX+EMZYNTZRZYn0pLTARBdLQDAFLFEjNVMDP94+1Dmw259677+Xee+659/18PM7j7rP23uusvc9d+3z22nutrYjAzMzMzMy22qnRBTAzMzMz62kcJJuZmZmZlThINjMzMzMrcZBsZmZmZlbiINnMzMzMrMRBspmZmZlZiYNk63SS7pD0T12U979J+kZX5N3G575V0qOSnpF0aJ35IekV3V2unkbS6yQ90OhytJekRySdVGG50fm73rmVZT4j6V87t4TWbHb0WCXpOEmrOrNMpfy/Junjhff/LOlP+Rg3LP/dvws+d6mk4zo730aQ9AVJ/9zocljXcZDch+XA4K/5YFh7/Vejy1VT70ciIj4dEV0SgLfh88C5EbF7RNzTgM9vChHx/yLi/zS6HI0iaQRwJvD1/P44SS/muvW0pAcknV1aR5I+Iul3uT6uzIH2LqXljpA0T9IGSesk/bqcV53yHJeD+o/VSd8uACuf4Ep6paT/lvSEpD9LWiLpw5L6VdgXMyRtzNu+QdIvJb2mMH8vSVdLeizvm99K+qSk3VrJc/ec3w/rzNvuRDWX4YbC+0GSLsv7+BlJD+X3w9vanvZq4LGqkoh4f0R8CkBSf+CLwBvyMe7J/PfhHfkMSbMkXVr63AMj4o4dybcH+Tzwb5IGNLog1jUcJNub88Gw9jq30QXqoUYBSxtZgNZaL3tCfgbAFGBeRPy1kLYmInYHBgEfAq6SVDyR+E/gHFJwvQdwCnAiMKe2QA4ubwd+BrwCGAb8c162NWcB63Le7SLpb4BfAY8CB0XEYOB0YEIuZxXfzts+AlgAfDefFAwF7gR2BV4TEXsArwf2BP6mlfz+AXgeeL2kl7dzewYAPwUOBE4mfR+vAZ4EjmhPXr3Qy4CBNPgY113qHfuqnPiVl4+Ix4DfAqd2Vtmsh4kIv/roC3gEOKlO+i7ABmB8IW0E8FfgpcAQ4H+BtcD6PD2ysOwdwD/l6RnADYV5o4EAds7vzwaWA08DDwPvy+m75c97EXgmv/auk9+ppAP7hvy5Y0vbdz6wBPgz8G1gYAv7YifgIuAPwOPAdcDgvC+eyWX+C/BQC+sH8Io8PTivvzbndxGwU57XD/gC8ATwe+Dc4v5o4Tv6WN6G54GdgaOAX+Ztvhc4rrD8GODneX/+BLiitr8K+34qsBL4eU7/x/wdrAduBUbldAFfyvvjKeC+2v8EMBFYlj9nNXB+Tj8OWFUoz9j8vWzI39OphXmzcvl+kPP5FfA3LeyHWtnPJgVt64H3A4fnfbMB+K+2vs/C/PfkeU8C0ynUhbzuBcBDef4cYGi9/9865bwdeHfh/Tb7I6c9Dpyepw8ANgNHlJbZN3/fJ+T3C4Ar2lm/d8v7dRLwAjChtXLVqbs3AD/YgePLDLatqwfmfTccuDT/P+3UzjxvB2YCv6n9z9Wrg/XKAPwT8Cdg9w5uz3HAKuCj+Tt8DHgLqS48SDoZ+bcWPntg3p9P5v/VhcDL8ryhwLXAmvx//b0W6lLtf/JpUt17a2HeK0gnUH8mHVu+XaEOz8rfwytJx7YgHetur3NM25V03PpD/owFwK553n8Df8zpPwcOzOnnABvz/94zwPcLx7RaXdsFuCxv+5o8vUtpf59X2N9nt/L9DAauzsutztvWL8+bAvwi74sn87xZwFeBeXn7T6Lt49U2y+f06cC1Ha0nfvXsl1uSbTsR8TzwXWByIfkdwM8i4nFSEHEtqXV1P1Iw29HbNB4H3kRq1Tkb+JKkV0fEX0itZGtiayv3muKKkl4JzAb+lRTEzwO+X7r09Q5Sq9EY4GDSwbKeKfl1PLA/sDsp6Ho+UksYwN9GRGutXDWXkw7Y+wPHklrxapfF35u36xDg1aQf2bZMBv6e1Mr2MlJQeSnpx/V84Dv5Mj/At4Bfk1oaZ5CCwbJjST8Gb5R0GvBvwNtI+/D/kfYpwBuAY0g/ooNJ+/LJPO9q0gnNHsB4UvCyjXwJ9/vAj0knV9OAG0utqJOAT5JOvFaQAqDWHEkKLN9J+kGdTvpxOxB4h6Rj83JTqPN95nKNI/3YvYd04jUMGFn4jGmk7+XYPH89KZiv4iCg7j3ZknaSdCopSFyRk08kBUK/Li4bEY8Cd5FaTF9CavG8uWIZat5GCk7+m3Tyc1Y71z+pA59ZV751ZArwaEQ8kfP+bkS82I48RpECpxvzq72t4ycBP4qIZ9q5XtHLSQHvPsDFwFXAu4HDgNcBH5c0ps56Z5Hq0L6k/7f3k46bANcDLyH9D7+UFMjV81D+jMGkOnODpL3yvE+R6tkQ0v/y5Tm9tToMQEQ8mD8bYM+IOKHOZ38+b+PfkY47HyU1YAD8kFQnX0o6ebkx53tlnv73fPx+c518p5NO+g8B/pbUon9RYf7Lc7n3IZ3cXyFpSN29k4LYTaQThkPzthdvdzmS1BDzMrYeZ96Vp/cgnaS3dbwqLr8gpy3PZbfeqNFRul+Ne5HO6J8hnTXXXu/N806i0GpKOgs/s4V8DgHWF97fQcWW5Dp5fQ/4lzx9HNu3wm3JD/g4MKcwbydSC8Jxhe0rtur9O/C1Fj73p8AHCu//D6kVpNbivV0rVWn9IB2c+5FaTsYV5r0PuCNP305uLS/s57Zakv+x8P5jwPWlZWoB0H6kH4mXFObdwPYtyfsX5v8QmFrah8+SToBOILWQHUWpxY/UEv0+YFApfct3RvpB/2NxXVIAPiNPzwK+UZg3EfhtC/uhVvZ9CmlPAu8svP8O8K9tfZ+k4Oamwrzd8ndWaxlaDpxYmL9XYd1aOVr6vjYCryrtjxdJdet5UqvxvxbmXwTc1UJeN5GCsH3yZ76q3nKt/E/+BLgsT08mXdno31LdqlN3NwInt+cz69TVF/K2P0763z8sz/sd8P525ncRsDhP75P35aHlOlinDLX//9uAz+7A9hxHCmxrrZN75M88srDM3cBb6nz2P5Ku/hxcynOv/P8xpIXP2+47KsxfDJyWp68DrqRwRS+nt1aHZwGXlurXzoX5tWPaTnm7/7bCPtozrze4/BmFZR5ha117CJhYmPdG4JHS/i6W6XHgqDqf+zJS/dq1kDYZmJ+npwAr62z/dYX3VY5X19X57NcDD3f0/8qvnv1yS7K9JSL2LLyuyunzgZdIOlLSaFIgfAuApJdI+rqkP0h6inSJbc/23tOV8zpF0l25I9IGUqBUtRPN3qTLfwBEapV6lPQDWvPHwvSzpBbFNvPK0zuTDr7tMRzoXyevWpn2zmWsKU63pLjMKOD03BFqQ95nR5N+bPcG1kXEs23kX87vy4W81pEu0e4TEbeTWl+vAB6XdKWkQXm9fyB9V3+Q9LNih6yCvUkth8XWwuK+gOrfT82fCtN/rfO+tn5r3+c230GkqxbF1rVRwC2FfbKcFJBV+V9Yz/b3666JiD1JV0v+kxS41DxB+u7q2SvPX08KpFpabjuS9iW1ot+Yk/6H1AL69/n9JtL/aVl/UnAMaZ9U/swWzMnHlZdGxAkRcfcO5H0mW1spV5NuLyi2jm9m+23q7O15MiI25+laS3BL/4NF15NOZm+StEbSv+crLfuS6uz6tj5Y0pmSFhf+L8ez9Vj5UVK9/bXS6BH/CNBGHa5qOOl/56E6Zeon6bO5A+RTpAC4tk4V9erp3oX3T0bEpsL7lo4Ro0jf9WOF/fN1UotwTVvHwirHq3p57EE6EbReyEGy1ZV/COaQzsYnA/8bEU/n2eeRWuaOjIhBpMt5kA7SZX8hXUqs2dLZJl+C/Q7pUt7LciAxr5BPtFHMNaSDYy0/kX50Vre1fW3lxdZW2T/VX7xFT5B+lMt51cr0GNte2t+3Qp7F/fAoqSW5eGKzW0R8Nuc9NF+eby3/cn7vK+W3a0T8EiAi/jMiDgPGkS7ZfiSnL4yI00g/Qt+j0MmsYA2wr6Ticaa4L7pSa9/nYxT2S95fwwrLPgqcUtonA3Ng1pYlpP20nUi3MX0MOEhS7Tab20n7aJuOYznIPQr4aT7puZN0YlLVe0jH9+9L+iPpMvNAtgaVK4HhkrYEHLn+jGJr0PKTdn5me/wEeGvpf6NFkv6OdEn/Qkl/zNt0JPCuQieslaQW0aIxbLs9b2xt9IyuEhEbI+KTETGOdMvCm0hB/6OkOrtna+vnW02uIvVhGJaPlfeTj5UR8ceIeG9E7E26wvOV2kgfLdXhdngCeI76HSrfBZxGuiI2mK37v0PHcFI9XdPCsq15lNSSPLxQZwdFxIGFZeqVpZhW5XhVL4+xpL4h1gs5SLbWfIt07+cZebpmD1KLyYbcS/0TreSxGDhG0n6SBgMXFuYNIHXcWAtsknQK6T6ymj8Bw/J69cwB/l7SiblV5jzSgfKXVTewYDbwIUljcuDwaVLnl01trLeNwsnFTEl75B+3D5Nue6iV+V8k7ZN/GD/WQlYtuQF4s6Q35lacgUrDeY2MiD8Ai4AZkgbk1t169wEWfY0UeBwIIGmwpNPz9OH5SkJ/0snOc8CLOe8zJA2OiI2kDkH17i39Fanl56OS+iuNjfpm0m0EXa217/Nm4E2Sjs73r1/CtsfCr5G+v1GQhnXL925XMY90L3NdEfECqQPUxfn9g/nzbpR0VP5ODySdPP4kIn6SV/0oMEVpqLhhuVx/K6mlfXkW6b7VQwqvfwAmShoWEStJ38/nlIZV24UUPG0k3QsNqV7/naT/UB5JQtIrJN1QC+qUhpGcUnHfFH2R1LL+zcJ+3kfSFyUd3ML23EYK9GrbM57Uoaw2wse3gYskjVS6//sk0v9b7b7q60nB1HckvSovM0xpPOOJuQyzJM3qwPa0StLxkg5Sutr2FGk/vxhpdIQfkoLaIbmeHFMni91IAdranN/Zeftr+Z8uqXbyvT4v+2JLdbg9Zc8tq9cAX5S0d/4ffU3+n9mDdMx9ktQY8unS6n8i9QloyWzSdzZCaRi+i9l6rGxPGR8j3Uv8BaVh/naS9Dfa2kehio4er44lfYfWCzlItu9r23GSb6nNiIhfkQ6se7PtQeAy0o/TE6Qf1B+1lHlE3Eb68VpCul/vfwvzngb+LylwXE9qlZhbmP9b0kH04XwJrXgZjoh4gNRp5vJcljeThrR7ob07gfQjcD3p1pHfk35MpnUgH/J6fyG13i0gnWBck+ddRTqYLwHuIQVVm0iXitsUqUNXrbPdWtKP/kfYWpfPYOuwVpeS9v3zreR3C/A50mXgp0itU7WgY1Au73q2jgTxH3nee4BH8jrvz59bzvsF0ndyCun7+QrpvvbfVtnWHdTi9xkRS4EPkr6Xx0jbVxwz+Muk/8MfS3qa9D9+ZMXPvY4UiO7aRtn2k1Q7gTkX+AYpOHiGVJ/uoNCKm1v2T8ivhyWtI92DOq+cuaSjSK1zV+QWxtprLqnDYK1D7jtJVwJWkFrLTgT+PiKey5/5EOl/aTSwVNKfScH7IuDpfIIxjK1BdWURsY7UoroR+FXezz8ljZCworispIGkDmeXl7bn96TvuNY6fgnpBHkB6Tv9d+CMiLg/f+bzpBbP35IC7qdInVyHkwIkSFcYftHe7ang5aRg/SnS7Ts/y2WHVJc25nI9TuqIvI2IWEY6ubqTFHgeVCrn4aT9+Azpf/dfIo1x3Fodbo/zSSNjLCTdkvU50jHnupzvatKIG+X/hauBcfn4/b06+V5K+n9akvP/TU7riDNJDS/LSNt7M+24vaYjxyuljpPjSFfTrBdSRFtXQ8ysq+TW869FxKg2F+5Y/t8mdYZrrbXfOpGkTwOPR8RljS5LV5J0NPDBiJjc5sJNIAf995I6121sa3kzSV8gdXD/SqPLYl3DQbJZN8otjMeTWpNfRmqZuysiOuUxxpIOJ7X0/J5068r3SA9r8FMCzczM2sG3W5h1L5HuFV1Put1iOfn+1E7yctKl+mdIIyn8swNkMzOz9nNLspmZmZlZiVuSzczMzMxKHCSbmZmZmZU4SDYzMzMzK3GQbGZmZmZW4iDZzMzMzKzEQbKZmZmZWUmlIFnSyZIekLRC0gV15o+S9FNJSyTdUXiGfG3+IEmrJP1XZxXczMzMzKyrtDlOsqR+wIPA64FVpGe3T87Pkq8t89/A/0bENyWdAJwdEe8pzP8yMAJYFxHntvZ5w4cPj9GjR3dwc8x6n7vvvvuJiBhRTpd0MvBloB/wjYj4bGn+fsA3gT3zMhdExDxJZwAfKSx6MPDqiFgs6Q5gL+Cved4bIuLx1srnOmu2rZbqbE/g+mq2rdbq684V1j8CWBERDwNIugk4DVhWWGYc8OE8PZ/0KFzy8oeRHr/7I2BCWx82evRoFi1aVKFYZn2DpD/USesHXEHh5FXS3OLJK3ARMCcivippHDAPGB0RNwI35nwOAr4XEYsL650REZUroeus2bbq1dmewvXVbFut1dcqt1vsAzxaeL8qpxXdC7wtT78V2EPSMEk7AV8Azm+jgOdIWiRp0dq1aysUyazP23LyGhEvALWT16IABuXpwcCaOvlMzuuamZlZQWd13DsfOFbSPcCxwGpgM/ABYF5ErGpt5Yi4MiImRMSEESN65BUqs56mysnrDODdklaRWpGn1cnnncDsUtq1khZL+rgk1ftwn9iamVlvVyVIXg3sW3g/MqdtERFrIuJtEXEoMD2nbQBeA5wr6RHg88CZkra5b9LMusxkYFZEjAQmAtfnqzsASDoSeDYi7i+sc0ZEHAS8Lr/eQx0+sTUzs96uSpC8EDhA0hhJA4BJwNziApKGF358LwSuAYiIMyJiv4gYTWptvi4ithsdw3qW2bNnM378ePr168f48eOZPbvc0Gg9QJsnr8BUYA5ARNwJDASGF+ZPotSKHBGr89+ngW+RbuuwHsz11cysa7QZJEfEJuBc4FZgOakj0FJJl0g6NS92HPCApAdJnfRmdlF5rYvNnj2b6dOnc/nll/Pcc89x+eWXM336dP/w9jxtnrwCK4ETASSNJQXJa/P7nYB3ULgfWdLOkobn6f7Am4D7sR7L9dXMrOu0OQRcd5swYUK4523jjB8/nssvv5zjjz9+S9r8+fOZNm0a99/veKkRJN0dEduNDCNpInAZaXi3ayJipqRLgEURMTePaHEVsDupE99HI+LHed3jgM9GxFGF/HYDfg70z3n+BPhwRGxurXyus43j+toztVRnewLXV7NttVZfHSTbNvr168dzzz1H//79t6Rt3LiRgQMHsnlzq7GSdZGe/IMLrrON5PraM/XkOuv62n1a6PdcWU+Lz3qr1uqrH0tt2xg7diwLFizYJm3BggWMHTu2QSUys5a4vpr1XBHR6qutZazxHCTbNqZPn87UqVOZP38+GzduZP78+UydOpXp06c3umhmVuL6ambWdao8cc/6kMmTJwMwbdo0li9fztixY5k5c+aWdDPrOVxfzcy6joNk287kyZP9I2vWJFxfzcy6hm+3MDMzMzMrcZBsZmZmZlbiINnMzMzMrMRBspmZmZlZiYNkMzMzM7MSB8lmZmZmZiUOks3MzMzMShwkm5mZmZmVOEg2MzMzMytxkGxmZmZmVuIg2axJSTpZ0gOSVki6oM78/STNl3SPpCWSJub00ZL+Kmlxfn2tsM5hku7Lef6nJHXnNpn1NRXq8TGSfiNpk6S3l+btJ+nHkpZLWiZpdHeV26wvcJBs1oQk9QOuAE4BxgGTJY0rLXYRMCciDgUmAV8pzHsoIg7Jr/cX0r8KvBc4IL9O7qptMOvrKtbjlcAU4Ft1srgO+I+IGAscATzedaU163scJJs1pyOAFRHxcES8ANwEnFZaJoBBeXowsKa1DCXtBQyKiLsiIkg/wG/p3GKbWUGb9TgiHomIJcCLxfQcTO8cEbfl5Z6JiGe7qdxmfYKDZLPmtA/waOH9qpxWNAN4t6RVwDxgWmHemHwbxs8kva6Q56o28jSzzlOlHrfklcAGSd/Ndfk/csv0diSdI2mRpEVr167dwSKb9R0Oks16r8nArIgYCUwErpe0E/AYsF++DePDwLckDWoln+34R9es4XYGXgecDxwO7E+6LWM7EXFlREyIiAkjRozovhKaNTkHyWbNaTWwb+H9yJxWNBWYAxARdwIDgeER8XxEPJnT7wYeIrVKrc75tJYneT3/6JrtuCr1uCWrgMX5Vo1NwPeAV3dy+cz6NAfJZs1pIXCApDGSBpA65s0tLbMSOBFA0lhSkLxW0ojaZVlJ+5M66D0cEY8BT0k6Ko9qcSbwP92zOWZ9UpV63Nq6e0qqnaWeACzrgjKa9VkOks2aUG45Ohe4FVhOGsViqaRLJJ2aFzsPeK+ke4HZwJTcIe8YYImkxcDNwPsjYl1e5wPAN4AVpBbmH3bbRpn1MVXqsaTDc7+C04GvS1qa191MutXip5LuAwRc1YjtMOutdm50AcysYyJiHqlDXjHt4sL0MuC1ddb7DvCdFvJcBIzv3JKaWUsq1OOFbHsbVHG524CDu7SAZn1YpZbkCoOdj5L00/zAgjskjczph0i6U9LSPO+dnb0BZmZmZmadrc0gueJg558HrouIg4FLgM/k9GeBMyPiQNJDCS6TtGdnFd7MzMzMrCtUaUmu8tCCccDteXp+bX5EPBgRv8vTa0hPA3JXeDMzMzPr0aoEyVUGO78XeFuefiuwh6RhxQUkHQEMIHUGMjMzMzPrsTprdIvzgWMl3QMcSxrncXNtZn7c7fXA2RHxYnllP5jAzMzMzHqSKkFym4OdR8SaiHhbfoLX9Jy2ASA/yesHwPSIuKveB/jBBGZmZmbWk1QJktsc7FzS8Py4W4ALgWty+gDgFlKnvps7r9hmZmZmjTV06FAkdegFdGi9oUOHNnir+442x0mOiE2SaoOd9wOuqQ12DiyKiLnAccBnJAXwc+CDefV3kB5cMEzSlJw2JSIWd+5mmJmZmXWv9evXk57R1H1qAbZ1vUoPE6kw2PnNpCd3lde7AbhhB8toZmbs+I9jd/+Ym5k1Mz9xz8ysSbQW5EpyEGxm1ok6a3QLMzMzM7New0GymZmZmVmJg2QzMzMzsxIHyWZmZmZmJQ6SzczMzMxKHCSbNSlJJ0t6QNIKSRfUmb+fpPmS7pG0RNLEnP56SXdLui//PaGwzh05z8X59dLu3CYzM7OewkPAmTUhSf2AK4DXA6uAhZLmRsSywmIXAXMi4quSxpHGOh8NPAG8OSLWSBpPelDQPoX1zoiIRd2xHWZmZj2VW5LNmtMRwIqIeDgiXgBuAk4rLRPAoDw9GFgDEBH3RMSanL4U2FXSLt1QZjMzs6bhINmsOe0DPFp4v4ptW4MBZgDvlrSK1Io8rU4+/wD8JiKeL6Rdm2+1+LhaeMSbpHMkLZK0aO3atR3eCDMzs57KQbJZ7zUZmBURI4GJwPWSttR5SQcCnwPeV1jnjIg4CHhdfr2nXsYRcWVETIiICSNGjOiyDTDrCyr0LzhG0m8kbZL09jrzB0laJem/uqfEZn2Dg2Sz5rQa2LfwfmROK5oKzAGIiDuBgcBwAEkjgVuAMyPiodoKEbE6/30a+Bbptg4z6yKF/gWnAOOAybkPQdFKYAqpTtbzKeDnXVVGs77KQXIfJ6nDL2uohcABksZIGgBMAuaWllkJnAggaSwpSF4raU/gB8AFEfGL2sKSdpZUC6L7A28C7u/yLTHr29rsXxARj0TEEuDF8sqSDgNeBvy4Owpr1pc4SO7jIqLFV5X51hgRsQk4lzQyxXLSKBZLJV0i6dS82HnAeyXdC8wGpkT64s4FXgFcXBrqbRfgVklLgMWklumrunfLzPqcKv0L6sq3T30BOL+N5dyHwKwDPAScWZOKiHmkDnnFtIsL08uA19ZZ71Lg0hayPawzy2hmXeoDwLyIWNXa1b2IuBK4EmDChAlu4TCryEGymZlZ41TpX9CS1wCvk/QBYHdggKRnImK7zn9m1n4Oks3MzBpnS/8CUnA8CXhXlRUj4ozatKQpwAQHyGadx/ckm5mZNUiV/gWSDs/jnZ8OfF3S0saV2KzvcEuymZlZA1XoX7CQdBtGa3nMAmZ1QfHM+iy3JJuZmZmZlThINjMzMzMr8e0WZmZmZh0QnxgEMwZ3/2dat3CQbGZmZtYB+uRT3f5wLUnEjG79yD7Lt1uYmZmZmZU4SDYzMzMzK6kUJEs6WdIDklZI2m6gckmjJP1U0hJJd0gaWZh3lqTf5ddZnVl4MzMzM7Ou0GaQLKkfcAVwCjAOmCxpXGmxzwPXRcTBwCXAZ/K6Q4FPAEcCRwCfkDSk84pvZmZmZtb5qrQkHwGsiIiHI+IF4CbgtNIy44Db8/T8wvw3ArdFxLqIWA/cBpy848U2MzMzM+s6VYLkfYBHC+9X5bSie4G35em3AntIGlZxXSSdI2mRpEVr166tWnYzs15l6NChSOrQC+jwukOHDm3wlpuZ9Tyd1XHvfOBYSfcAxwKrgc1VV46IKyNiQkRMGDFiRCcVycysuaxfv56I6PbX+vXrG73pZmY9TpUgeTWwb+H9yJy2RUSsiYi3RcShwPSctqHKumbWMRU61O4nab6ke3Kn2omFeRfm9R6Q9MaqeZqZmfUVVYLkhcABksZIGgBMAuYWF5A0XFItrwuBa/L0rcAbJA3JHfbekNPMbAdU7FB7ETAnn7xOAr6S1x2X3x9I6iPwFUn9KuZpZmYFHb3NqaOvIUM8/kF3afOJexGxSdK5pOC2H3BNRCyVdAmwKCLmAscBn5EUwM+BD+Z110n6FCnQBrgkItZ1wXaY9TVbOtQCSKp1qF1WWCaA2vNLBwNr8vRpwE0R8Tzwe0krcn5UyNPMzLIdedqepG5/Wp+1T6XHUkfEPGBeKe3iwvTNwM0trHsNW1uWrZsNHTp0h+43rHUIaq8hQ4awbp3Ph7pQvU6xR5aWmQH8WNI0YDfgpGNuH5kAAA4cSURBVMK6d5XWrXWobStPIHW2Bc4B2G+//dpfejMzsx7OT9zr5dwRqE+bDMyKiJHAROD6wm1RO8Sdbc3MrLer1JJsZj1OlU6xU8njkkfEnZIGAsPbWNcdbc3MzHBLslmzarNDLbASOBFA0lhgILA2LzdJ0i6SxgAHAL+umKeZmVmf4JZksyZUsUPtecBVkj5E6sQ3JVIvkaWS5pA65G0CPhgRmwHq5dntG2dmZtYDOEg2a1IVOtQuA17bwrozgZlV8jSzriPpZODLpBPTb0TEZ0vzjwEuAw4GJuWO8kg6BPgqaQSbzcDMiPh2d5bdrLfz7RZmZmYNUHFs8pXAFOBbpfRngTMjojbe+WWS9uzaEpv1LW5JNjMza4w2xzuPiEfyvBeLK0bEg4XpNZIeB0YAG7q+2GZ9g1uSzczMGqPeeOf7tLBsiyQdAQwAHmph/jmSFklatHbt2g4V1KwvckuymVkPEZ8YBDMGN+ZzrSlJ2gu4HjgrIl6st0xEXAlcCTBhwgQ/4s2sIgfJZmY9hD75VEMeUyuJmNHtH2vVxjtvkaRBwA+A6RFxV1vLm1n7+HYLMzOzxujw2OR5+VuA62ojXphZ53KQbGZm1gARsQmojU2+HJhTG+9c0qkAkg6XtAo4Hfi6pNrY5e8AjgGmSFqcX4c0YDPMei3fbmFmZtYgFcY7X0i6DaO83g3ADV1eQLM+zC3JZmZmZmYlDpLNzMzMzEocJJuZmZmZlThINjMzMzMrcce9Xs4PJzAzMzNrPwfJvZwfTmBmZmbWfr7dwqxJSTpZ0gOSVki6oM78LxXGT31Q0oacfnwhfbGk5yS9Jc+bJen3Hne1cSR1+2vIkCGN3mwzsx7HLclmTUhSP+AK4PXAKmChpLkRsay2TER8qLD8NODQnD4fOCSnDwVWAD8uZP8RP8GrMXbkqo+khlw1MjPrrdySbNacjgBWRMTDEfECcBNwWivLTwZm10l/O/DDiHi2C8poZmbWtBwkmzWnfYBHC+9X5bTtSBoFjAFurzN7EtsHzzMlLcm3a+zSGYU1MzNrNg6SzXq/ScDNEbG5mChpL+Ag4NZC8oXAq4DDgaHAx+plKOkcSYskLVq7dm3XlNrMzKyBKgXJFToI7SdpvqR7cgvUxJzeX9I3Jd0nabmkCzt7A8z6qNXAvoX3I3NaPfVaiwHeAdwSERtrCRHxWCTPA9eSbuvYTkRcGRETImLCiBEjOrQBZmZmPVmbQXKhg9ApwDhgsqRxpcUuAuZExKGkH+Sv5PTTgV0i4iDgMOB9kkZ3TtHN+rSFwAGSxkgaQKp3c8sLSXoVMAS4s04e292nnFuXkSTgLcD9nVxuMzOzplClJblKB6EAak+PGAysKaTvJmlnYFfgBeCpHS61WR8XEZuAc0m3SiwnnaQulXSJpFMLi04CborSsAf5ZHVf4GelrG+UdB9wHzAcuLRrtsDMzKxnqzIEXL0OQkeWlpkB/DgPM7UbcFJOv5kUUD8GvAT4UESs25ECm1kSEfOAeaW0i0vvZ7Sw7iPU6egXESd0XgnNzMyaV2d13JsMzIqIkcBE4HpJO5FaoTcDe5N6158naf/yyu4EZGZmZmY9SZUguUoHoanAHICIuBMYSLpU+y7gRxGxMSIeB34BTCh/gDsBmZmZmVlPUiVIrtJBaCVwIoCksaQgeW1OPyGn7wYcBfy2c4puZmZmZtY12gySK3YQOg94r6R7Sb3lp+SOQlcAu0taSgq2r42IJV2xIWZmZmZmnaVKx702OwhFxDLgtXXWe4Y0DJyZmZnVIelk4MtAP+AbEfHZ0vxjgMuAg4FJEXFzYd5ZpGFYAS6NiG92T6nNej8/cc/MzKxBKj6LYCUwBfhWad2hwCdII04dAXxC0pCuLrNZX+Eg2czMrHHafBZBRDySb1V8sbTuG4HbImJdRKwHbgNO7o5Cm/UFDpLNzJqEpBZfbc2vLWM9Tr1nEWw3hvmOrOthVs06xkGymVmTiIgdelnf5GFWzTqmUsc9a26NaEEaMsS3xZmZVVDlWQStrXtcad07OqVUZuYgubfbkdYjSW59MjPrWlueRUAKeieRHsRVxa3Apwud9d4AXNj5RTTrm3y7hZmZWYNUeRaBpMMlrSINqfr1/OwBImId8ClSoL0QuCSnmVkncEuymZlZA1V4FsFC0q0U9da9BrimSwtoHVLlVsfWlvGV3MZzkGxmZmbWyRzkNj/fbmFmZmZmVuIg2axJSTpZ0gOSVki6oM78L0lanF8PStpQmLe5MG9uIX2MpF/lPL8taUB3bY+ZmVlP4iDZrAlVeZRtRHwoIg6JiEOAy4HvFmb/tTYvIk4tpH8O+FJEvAJYD0zt0g0xMzProRwkmzWnNh9lWzIZmN1ahko9SE4Abs5J3wTe0gllNTMzazoOks2aU+VH2UoaBYwBbi8kD8yPqb1LUi0QHgZsyENStZWnH3NrZma9mke3MOv9JgE3R8TmQtqoiFgtaX/gdkn3AX+ummFEXAlcCTBhwgR34TYzs17HLclmzak9j7KdROlWi4hYnf8+THqM7aHAk8Cekmonz+15PK6ZmVmv4iDZrDlteZRtHoFiEjC3vJCkVwFDgDsLaUMk7ZKnhwOvBZZFGtRzPvD2vOhZwP906VaYmZn1UA6SzZpQlUfZZpOAm2LbUe3HAosk3UsKij8bEcvyvI8BH5a0gnSP8tVdvS1mZmY9ke9JNmtSbT3KNr+fUWe9XwIHtZDnw6SRM8zMzPo0tySbmZmZmZU4SDYzMzMzK3GQbGZmZmZW4iDZzMzMzKzEQbKZmZmZWYmDZDMzMzOzkkpBsqSTJT0gaYWkC+rM30/SfEn3SFoiaWJh3sGS7pS0VNJ9kgZ25gaYmZmZmXW2NsdJltQPuAJ4PbAKWChpbuHhAwAXkR5m8FVJ40hjt47Oj7e9AXhPRNwraRiwsdO3wszMzMysE1VpST4CWBERD0fEC8BNwGmlZQIYlKcHA2vy9BuAJRFxL0BEPBkRm3e82GZmZr1Dhau1u0j6dp7/K0mjc3p/Sd/MV2mXS7qwu8tu1ptVCZL3AR4tvF+V04pmAO+WtIrUijwtp78SCEm3SvqNpI/W+wBJ50haJGnR2rVr27UBZmZmzapwtfYUYBwwOV+RLZoKrI+IVwBfAj6X008HdomIg4DDgPfVAmgz23Gd1XFvMjArIkYCE4HrJe1Eup3jaOCM/Petkk4srxwRV0bEhIiYMGLEiE4qkpmZWY9X5WrtacA38/TNwImSRLqKu1u+tXFX4AXgqe4ptlnvVyVIXg3sW3g/MqcVTQXmAETEncBAYDip1fnnEfFERDxLamV+9Y4W2szMrJeocrV2yzIRsQn4MzCMFDD/BXgMWAl8PiLWlT/AV2vNOqZKkLwQOEDSGEkDgEnA3NIyK4ETASSNJQXJa4FbgYMkvSSf6R4LLMPMzMx21BHAZmBvYAxwnqT9ywv5aq1Zx7QZJOez1nNJAe9y0igWSyVdIunUvNh5wHsl3QvMBqZEsh74IinQXgz8JiJ+0BUbYmZm1oSqXK3dskxucBoMPAm8C/hRRGyMiMeBXwATurzEZn1Em0PAAUTEPNKtEsW0iwvTy4DXtrDuDaRh4MzMzGxbW67WkoLhSaTgt2gucBZwJ/B24PaICEkrgRNI/YB2A44CLuu2kpv1cn7inlmTqjBs1JckLc6vByVtyOmHFB7ws0TSOwvrzJL0+8J6h3TnNpn1NRWv1l4NDJO0AvgwUKvvVwC7S1pKCravjYgl3bsFZr1XpZZkM+tZqjzkJyI+VFh+GnBofvsscGZE/E7S3sDdkm6NiA15/kci4uZu2RAzq3K19jnScG/l9Z6pl25mncMtyWbNqcqwUUWTSf0FiIgHI+J3eXoN8Djg3jxmZmYFDpLNmlOVYaMAkDSK1PP99jrzjgAGAA8Vkmfm2zC+JGmXFvL0kFJmZtarOUg26/0mATeXHwkvaS/geuDsiHgxJ18IvAo4HBgKfKxehh5SyszMejsHyWbNqcqwUTWTyLda1EgaBPwAmB4Rd9XSI+KxPHzj88C1pNs6zMzM+hwHyWbNqcpDfpD0KmAIaeioWtoA4BbgunIHvdy6TH7k7VuA+7tsC8zMzHowj25h1oQiYpOk2rBR/YBrasNGAYsiohYwTwJuiogorP4O4BjSkFJTctqUiFgM3ChpBCDSA4De3w2bY2Zm1uM4SDZrUm0NG5Xfz6izXosP+ImIEzqxiGZmZk3Lt1uYmZmZmZU4SDYzMzMzK3GQbGbWxGbPns348ePp168f48ePZ/bs2W2vZGYN4zrbPHxPsplZk5o9ezbTp0/n6quv5uijj2bBggVMnToVgMmTJze4dGZW5jrbXNySbGbWpGbOnMnVV1/N8ccfT//+/Tn++OO5+uqrmTlzZqOLZmZ1uM42F7ck93FpONyOzd92VDEz627Lly/n6KOP3ibt6KOPZvny5Q0qkZm1xnW2ubgluY+LiA6/zKyxxo4dy4IFC7ZJW7BgAWPHjm1QicysNa6zzcVBsplZk5o+fTpTp05l/vz5bNy4kfnz5zN16lSmT5/e6KKZWR2us83Ft1uYmTWpWkefadOmsXz5csaOHcvMmTPdAcish3KdbS4Oks3MmtjkyZP9A2vWRFxnm4dvtzAzMzMzK3GQbGZmZmZWop42SoGktcAfGl0Osx5kVESMaHQhWuI6a7adHltnXV/NttNife1xQbKZmZmZWaP5dgszMzMzsxIHyWZmZmZmJQ6SzczMzMxKHCSbmZmZmZU4SDYzMzMzK3GQbGZmZmZW4iDZzMzMzKzEQbKZmZmZWYmDZDMzMzOzkv8Pt9xzXyL+5EkAAAAASUVORK5CYII=\n",
            "text/plain": [
              "<Figure size 864x216 with 3 Axes>"
            ]
          },
          "metadata": {
            "needs_background": "light"
          }
        }
      ]
    }
  ]
}